In [129]:
import pandas as pd

In [130]:
cola_data = pd.read_excel("data/Cola.xlsx")
cola_data

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [131]:
cola_data.shape

(103, 12)

In [132]:
profil_and_loss = cola_data.iloc[2:20, 1:]

profil_and_loss = profil_and_loss.T
profil_and_loss.columns = [
    "Financial Year",
    "NET OPERATING REVENUES",
    "Cost of goods sold",
    "Gross Profit",
    "Selling, general and administrative expenses",
    "Other operating charges",
    "Operating Income",
    "Interest income",
    "Interest expense",
    "Equity income (loss) - net",
    "Other income (loss) - net",
    "Income before income taxes",
    "Income taxes",
    "CONSOLIDATED NET INCOME",
    "Less: Net income attributable to noncontrolling interests",
    "Net income from continuing operations",
    "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",
    "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY",
]
profil_and_loss.reset_index(drop=True, inplace=True)
profil_and_loss = profil_and_loss.iloc[1:].reset_index(drop=True)
profil_and_loss

,Financial Year,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,CONSOLIDATED NET INCOME,Less: Net income attributable to noncontrolling interests,Net income from continuing operations,"Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,82,NaN,NaN,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,50,NaN,NaN,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,62,NaN,NaN,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,67,NaN,NaN,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,42,NaN,NaN,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,26,NaN,NaN,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,15,7366,0,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,23,6550,0,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1283,35,1182,101,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6476,42,6727,-251,6434

In [133]:
profil_and_loss.columns

Index(['Financial Year', 'NET OPERATING REVENUES', 'Cost of goods sold',
       'Gross Profit', 'Selling, general and administrative expenses',
       'Other operating charges', 'Operating Income', 'Interest income',
       'Interest expense', 'Equity income (loss) - net',
       'Other income (loss) - net', 'Income before income taxes',
       'Income taxes', 'CONSOLIDATED NET INCOME',
       'Less: Net income attributable to noncontrolling interests',
       'Net income from continuing operations',
       'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
       'NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY'],
      dtype='str')

In [134]:
cols = ['NET OPERATING REVENUES', 'Cost of goods sold',
       'Gross Profit', 'Selling, general and administrative expenses',
       'Other operating charges', 'Operating Income', 'Interest income',
       'Interest expense', 'Equity income (loss) - net',
       'Other income (loss) - net', 'Income before income taxes',
       'Income taxes', 'CONSOLIDATED NET INCOME',
       'Less: Net income attributable to noncontrolling interests',
       'Net income from continuing operations',
       'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
       'NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY']
profil_and_loss[cols] = profil_and_loss[cols].apply(pd.to_numeric).astype("Int64")

In [135]:
profil_and_loss.rename(
    columns={
        "NET OPERATING REVENUES": "Revenue",
        "Cost of Goods Sold": "COGS",
        "Gross Profit": "Gross_Profit",
        "Selling, General and Administrative Expenses": "SGA",
        "Other Operating Charges": "Other_Op_Charges",
        "Operating Income": "Operating_Income",
        "Interest Income": "Interest_Income",
        "Interest Expense": "Interest_Expense",
        "Equity Income (Loss) — Net": "Equity_Income",
        "Other Income (Loss) — Net": "Other_Income",
        "Income Before Income Taxes": "PreTax_Income",
        "Income Taxes": "Taxes",
        "CONSOLIDATED NET INCOME": "Net_Income",
        "Less: Net income attributable to noncontrolling interests": "NonControl_Int",
        "Net income from continuing operations": "Cont_Income",
        "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest": "Disc_Income",
        "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY": "Shareholder_Income",
    },
    inplace=True,
)

### Gross Profit
profil_and_loss["Gross_Profit"] = (
    profil_and_loss["Revenue"]
    - profil_and_loss["COGS"]
)

### Operating Income
profil_and_loss["Operating_Income"] = (
    profil_and_loss["Gross_Profit"]
    - profil_and_loss["SGA"]
    - profil_and_loss["Other_Op_Charges"]
)

### Net Interest
profil_and_loss["Net_Interest"] = (
    profil_and_loss["Interest_Income"]
    - profil_and_loss["Interest_Expense"]
)

### Non Operating Income
profil_and_loss["Non_Operating_Income"] = (
    profil_and_loss["Interest_Income"]
    - profil_and_loss["Interest_Expense"]
    + profil_and_loss["Equity_Income"]
    + profil_and_loss["Other_Income"]
)

### PreTax Income
profil_and_loss["PreTax_Income"] = (
    profil_and_loss["Operating_Income"]
    + profil_and_loss["Non_Operating_Income"]
)

### Net Income
profil_and_loss["Net_Income"] = (
    profil_and_loss["PreTax_Income"]
    - profil_and_loss["Taxes"]
)

### Continuing Income
profil_and_loss["Cont_Income"] = (
    profil_and_loss["Net_Income"]
    - profil_and_loss["Disc_Income"].fillna(0)
)

### Shareholder Income
profil_and_loss["Shareholder_Income"] = (
    profil_and_loss["Net_Income"]
    - profil_and_loss["NonControl_Int"]
)

In [136]:
profil_and_loss

,Financial Year,Revenue,Cost of goods sold,Gross_Profit,"Selling, general and administrative expenses",Other operating charges,Operating_Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,Net_Income,NonControl_Int,Cont_Income,Disc_Income,Shareholder_Income
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,82,<NA>,<NA>,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,50,<NA>,<NA>,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,62,<NA>,<NA>,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,67,<NA>,<NA>,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,42,<NA>,<NA>,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,26,<NA>,<NA>,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,15,7366,0,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,23,6550,0,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1283,35,1182,101,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6476,42,6727,-251,6434

In [137]:
profil_and_loss.columns

Index(['Financial Year', 'Revenue', 'Cost of goods sold', 'Gross_Profit',
       'Selling, general and administrative expenses',
       'Other operating charges', 'Operating_Income', 'Interest income',
       'Interest expense', 'Equity income (loss) - net',
       'Other income (loss) - net', 'Income before income taxes',
       'Income taxes', 'Net_Income', 'NonControl_Int', 'Cont_Income',
       'Disc_Income', 'Shareholder_Income'],
      dtype='str')

In [138]:
import pandas as pd
import numpy as np

# Formula dictionary using YOUR columns
formulas = {
    "Gross_Profit": lambda r: r["Revenue"] - r["Cost of goods sold"],
    "Operating_Income": lambda r: r["Gross_Profit"]
    - r["Selling, general and administrative expenses"]
    - r["Other operating charges"],
    "Income before income taxes": lambda r: r["Operating_Income"]
    + r["Interest income"]
    - r["Interest expense"]
    + r["Equity income (loss) - net"]
    + r["Other income (loss) - net"],
    "Net_Income": lambda r: r["Income before income taxes"] - r["Income taxes"],
    "Cont_Income": lambda r: r["Net_Income"]
    - (0 if pd.isna(r["Disc_Income"]) else r["Disc_Income"]),
    "Shareholder_Income": lambda r: r["Net_Income"] - r["NonControl_Int"],
}

failed_records = []

# Row-by-row validation
for idx, row in profil_and_loss.iterrows():

    for formula_name, formula in formulas.items():

        try:

            expected = formula(row)
            actual = row[formula_name]

            # Skip if both missing
            if pd.isna(actual) and pd.isna(expected):
                continue

            # Safe comparison
            if not np.isclose(float(actual), float(expected), rtol=1e-5):

                failed_records.append(
                    {
                        "Index": idx,
                        "FY": row["Financial Year"],
                        "Formula": formula_name,
                        "Actual": actual,
                        "Expected": expected,
                    }
                )

        except Exception as e:

            failed_records.append(
                {
                    "Index": idx,
                    "FY": row["Financial Year"],
                    "Formula": formula_name,
                    "Error": str(e),
                }
            )

# Print only failed validations
if len(failed_records) == 0:
    print("All formulas validated successfully.")

else:
    for fail in failed_records:

        print(
            f"Row={fail['Index']} | "
            f"FY={fail['FY']} | "
            f"Formula={fail['Formula']} FAILED | "
            f"Actual={fail.get('Actual')} | "
            f"Expected={fail.get('Expected')}"
        )

Row=0 | FY=FY '09 | Formula=Cont_Income FAILED | Actual=None | Expected=None
Row=1 | FY=FY '10 | Formula=Cont_Income FAILED | Actual=None | Expected=None
Row=2 | FY=FY '11 | Formula=Cont_Income FAILED | Actual=None | Expected=None
Row=3 | FY=FY '12 | Formula=Cont_Income FAILED | Actual=None | Expected=None
Row=4 | FY=FY '13 | Formula=Cont_Income FAILED | Actual=None | Expected=None
Row=5 | FY=FY '14 | Formula=Cont_Income FAILED | Actual=None | Expected=None
Row=8 | FY=FY '17 | Formula=Net_Income FAILED | Actual=1283 | Expected=1182
Row=9 | FY=FY '18 | Formula=Net_Income FAILED | Actual=6476 | Expected=6727

In [139]:
profil_and_loss

,Financial Year,Revenue,Cost of goods sold,Gross_Profit,"Selling, general and administrative expenses",Other operating charges,Operating_Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,Net_Income,NonControl_Int,Cont_Income,Disc_Income,Shareholder_Income
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,82,<NA>,<NA>,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,50,<NA>,<NA>,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,62,<NA>,<NA>,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,67,<NA>,<NA>,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,42,<NA>,<NA>,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,26,<NA>,<NA>,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,15,7366,0,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,23,6550,0,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1283,35,1182,101,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6476,42,6727,-251,6434

In [140]:
# profil_and_loss["Net income from continuing operations"] = profil_and_loss[
#     "Net income from continuing operations"
# ].fillna(0)

# profil_and_loss["Net income from continuing operations"] = (
#     profil_and_loss["CONSOLIDATED NET INCOME"]
#     - profil_and_loss["Less: Net income attributable to noncontrolling interests"]
# )

## or

# profil_and_loss["Net income from continuing operations"] = (
#     profil_and_loss["CONSOLIDATED NET INCOME"]
#     - profil_and_loss["Less: Net income attributable to noncontrolling interests"]
# ).fillna(0)

In [141]:
profil_and_loss

,Financial Year,Revenue,Cost of goods sold,Gross_Profit,"Selling, general and administrative expenses",Other operating charges,Operating_Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,Net_Income,NonControl_Int,Cont_Income,Disc_Income,Shareholder_Income
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,82,<NA>,<NA>,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,50,<NA>,<NA>,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,62,<NA>,<NA>,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,67,<NA>,<NA>,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,42,<NA>,<NA>,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,26,<NA>,<NA>,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,15,7366,0,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,23,6550,0,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1283,35,1182,101,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6476,42,6727,-251,6434

In [142]:
profil_and_loss.isna().sum()

Financial Year                                  0
Revenue                                         0
Cost of goods sold                              0
Gross_Profit                                    0
Selling, general and administrative expenses    0
Other operating charges                         0
Operating_Income                                0
Interest income                                 0
Interest expense                                0
Equity income (loss) - net                      0
Other income (loss) - net                       0
Income before income taxes                      0
Income taxes                                    0
Net_Income                                      0
NonControl_Int                                  0
Cont_Income                                     6
Disc_Income                                     6
Shareholder_Income                              0
dtype: int64

In [143]:
# profil_and_loss["NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY"] = (
#     profil_and_loss[
#         profil_and_loss[
#             "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY"
#         ]
#         - profil_and_loss["Less: Net income attributable to noncontrolling interests"]
#     ]
# )

In [144]:
# profil_and_loss.to_csv("data/cola_profile_loss.csv", index=False)

In [145]:
# profil_and_loss.shape

In [146]:
profil_and_loss.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Financial Year                                10 non-null     object
 1   Revenue                                       10 non-null     Int64
 2   Cost of goods sold                            10 non-null     Int64
 3   Gross_Profit                                  10 non-null     Int64
 4   Selling, general and administrative expenses  10 non-null     Int64
 5   Other operating charges                       10 non-null     Int64
 6   Operating_Income                              10 non-null     Int64
 7   Interest income                               10 non-null     Int64
 8   Interest expense                              10 non-null     Int64
 9   Equity income (loss) - net                    10 non-null     Int64
 10  Other income (loss) - net                     10 non-null     Int64
 11  Income before income taxes                    10 non-null     Int64
 12  Income taxes                                  10 non-null     Int64
 13  Net_Income                                    10 non-null     Int64
 14  NonControl_Int                                10 non-null     Int64
 15  Cont_Income                                   4 non-null      Int64
 16  Disc_Income                                   4 non-null      Int64
 17  Shareholder_Income                            10 non-null     Int64
dtypes: Int64(17), object(1)
memory usage: 1.7+ KB