In [173]:
import pandas as pd

In [174]:
cola_data = pd.read_excel("data/Cola.xlsx")
cola_data

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [175]:
cola_data.shape

(103, 12)

 ```python
 [
    "Financial Year", 
    "NET OPERATING REVENUES",
    "Cost of goods sold",
    "Gross Profit",
    "Selling, general and administrative expenses",
    "Other operating charges",
    "Operating Income",
    "Interest income",
    "Interest expense",
    "Equity income (loss) - net",
    "Other income (loss) - net",
    "Income before income taxes",
    "Income taxes",
    "CONSOLIDATED NET INCOME",
    "Less: Net income attributable to noncontrolling interests",
    "Net income from continuing operations",
    "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",
    "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY",
]
```

In [176]:
profil_and_loss = cola_data.iloc[2:20, 1:]

profil_and_loss = profil_and_loss.T
profil_and_loss.columns = [
    "Financial Year",
    "NET OPERATING REVENUES",
    "Cost of goods sold",
    "Gross Profit",
    "Selling, general and administrative expenses",
    "Other operating charges",
    "Operating Income",
    "Interest income",
    "Interest expense",
    "Equity income (loss) - net",
    "Other income (loss) - net",
    "Income before income taxes",
    "Income taxes",
    "CONSOLIDATED NET INCOME",
    "Less: Net income attributable to noncontrolling interests",
    "Net income from continuing operations",
    "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",
    "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY",
]
profil_and_loss.reset_index(drop=True, inplace=True)
profil_and_loss = profil_and_loss.iloc[1:].reset_index(drop=True)
profil_and_loss

,Financial Year,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,CONSOLIDATED NET INCOME,Less: Net income attributable to noncontrolling interests,Net income from continuing operations,"Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,82,NaN,NaN,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,50,NaN,NaN,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,62,NaN,NaN,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,67,NaN,NaN,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,42,NaN,NaN,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,26,NaN,NaN,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,15,7366,0,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,23,6550,0,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1283,35,1182,101,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6476,42,6727,-251,6434

In [177]:
cols = ['NET OPERATING REVENUES', 'Cost of goods sold',
       'Gross Profit', 'Selling, general and administrative expenses',
       'Other operating charges', 'Operating Income', 'Interest income',
       'Interest expense', 'Equity income (loss) - net',
       'Other income (loss) - net', 'Income before income taxes',
       'Income taxes', 'CONSOLIDATED NET INCOME',
       'Less: Net income attributable to noncontrolling interests',
       'Net income from continuing operations',
       'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
       'NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY']
profil_and_loss[cols] = profil_and_loss[cols].apply(pd.to_numeric).astype("Int64")

In [178]:
profil_and_loss

,Financial Year,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,CONSOLIDATED NET INCOME,Less: Net income attributable to noncontrolling interests,Net income from continuing operations,"Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,82,<NA>,<NA>,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,50,<NA>,<NA>,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,62,<NA>,<NA>,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,67,<NA>,<NA>,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,42,<NA>,<NA>,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,26,<NA>,<NA>,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,15,7366,0,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,23,6550,0,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1283,35,1182,101,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6476,42,6727,-251,6434

In [179]:
## This cells code for swaping the features for better understanding of data

(
    profil_and_loss["Net income from continuing operations"],
    profil_and_loss["CONSOLIDATED NET INCOME"],
) = (
    profil_and_loss["CONSOLIDATED NET INCOME"],
    profil_and_loss["Net income from continuing operations"],
)

(
    profil_and_loss["Less: Net income attributable to noncontrolling interests"],
    profil_and_loss[
        "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest"
    ],
) = (
    profil_and_loss[
        "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest"
    ],
    profil_and_loss["Less: Net income attributable to noncontrolling interests"],
)
profil_and_loss.columns = [
    "Financial Year",
    "NET OPERATING REVENUES",
    "Cost of goods sold",
    "Gross Profit",
    "Selling, general and administrative expenses",
    "Other operating charges",
    "Operating Income",
    "Interest income",
    "Interest expense",
    "Equity income (loss) - net",
    "Other income (loss) - net",
    "Income before income taxes",
    "Income taxes",
    "Net income from continuing operations",
    "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",
    "CONSOLIDATED NET INCOME",
    "Less: Net income attributable to noncontrolling interests",
    "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY",
]

In [180]:
profil_and_loss

,Financial Year,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,Net income from continuing operations,"Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",CONSOLIDATED NET INCOME,Less: Net income attributable to noncontrolling interests,NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,<NA>,<NA>,6906,82,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,<NA>,<NA>,11837,50,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,<NA>,<NA>,8646,62,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,<NA>,<NA>,9086,67,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,<NA>,<NA>,8626,42,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,<NA>,<NA>,7124,26,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,0,7366,15,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,0,6550,23,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1182,101,1283,35,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6727,-251,6476,42,6434

### Formula - Calculation Heppen in this Data

| Feature                                                                                                               | Type                | Formula                                                                                            |
| --------------------------------------------------------------------------------------------------------------------- | ------------------- | -------------------------------------------------------------------------------------------------- |
| Financial Year                                                                                                        | Provided            | —                                                                                                  |
| NET OPERATING REVENUES                                                                                                | Provided            | —                                                                                                  |
| Cost of goods sold                                                                                                    | Provided            | —                                                                                                  |
| **Gross Profit**                                                                                                      | Calculated          | NET OPERATING REVENUES − Cost of goods sold                                                        |
| Selling, general and administrative expenses                                                                          | Provided            | —                                                                                                  |
| Other operating charges                                                                                               | Provided            | —                                                                                                  |
| **Operating Income**                                                                                                  | Calculated          | Gross Profit − Selling, general and administrative expenses − Other operating charges              |
| Interest income                                                                                                       | Provided            | —                                                                                                  |
| Interest expense                                                                                                      | Provided            | —                                                                                                  |
| Equity income (loss) - net                                                                                            | Provided            | —                                                                                                  |
| Other income (loss) - net                                                                                             | Provided            | —                                                                                                  |
| **Income before income taxes**                                                                                        | Calculated          | Operating Income + Interest income − Interest expense + Equity income (loss) + Other income (loss) |
| Income taxes                                                                                                          | Provided            | —                                                                                                  |
| **Net income from continuing operations**                                                                             | Calculated          | Income before income taxes − Income taxes                                                          |
| **Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest** | Provided / Reported | —                                                                                                  |
| **CONSOLIDATED NET INCOME**                                                                                           | Calculated          | Net income from continuing operations + Income (Loss) from Discontinued Operations                 |
| Less: Net income attributable to noncontrolling interests                                                             | Provided            | —                                                                                                  |
| **NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY**                                                   | Calculated          | CONSOLIDATED NET INCOME − Less: Net income attributable to noncontrolling interests                |

In [181]:
profil_and_loss["Net income from continuing operations"] = (
    profil_and_loss["Income before income taxes"] - profil_and_loss["Income taxes"]
)

profil_and_loss[
    "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest"
] = profil_and_loss[
    "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest"
].fillna(0)

In [182]:
profil_and_loss

,Financial Year,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,Net income from continuing operations,"Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",CONSOLIDATED NET INCOME,Less: Net income attributable to noncontrolling interests,NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,0,6906,82,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,0,11837,50,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,0,8646,62,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,0,9086,67,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,0,8626,42,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,0,7124,26,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,0,7366,15,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,0,6550,23,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1182,101,1283,35,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6727,-251,6476,42,6434

In [183]:
## this cells code is for checking the validator code is working or not

# profil_and_loss.loc[5, "Gross Profit"] = 1000
# profil_and_loss.loc[5, "Gross Profit"]

In [184]:
import pandas as pd
import numpy as np

# Create separate validation dataframe
validation_df = pd.DataFrame()

# Optional: keep identifier column
validation_df['Financial Year'] = profil_and_loss['Financial Year']

# Validation checks
validation_df['Gross_Profit_valid'] = np.isclose(
    profil_and_loss['Gross Profit'],
    profil_and_loss['NET OPERATING REVENUES'] - profil_and_loss['Cost of goods sold'],
    equal_nan=True
)

validation_df['Operating_Income_valid'] = np.isclose(
    profil_and_loss['Operating Income'],
    profil_and_loss['Gross Profit']
    - profil_and_loss['Selling, general and administrative expenses']
    - profil_and_loss['Other operating charges'],
    equal_nan=True
)

validation_df['Income_before_taxes_valid'] = np.isclose(
    profil_and_loss['Income before income taxes'],
    profil_and_loss['Operating Income']
    + profil_and_loss['Interest income']
    - profil_and_loss['Interest expense']
    + profil_and_loss['Equity income (loss) - net']
    + profil_and_loss['Other income (loss) - net'],
    equal_nan=True
)

validation_df['Continuing_Operations_valid'] = np.isclose(
    profil_and_loss['Net income from continuing operations'],
    profil_and_loss['Income before income taxes']
    - profil_and_loss['Income taxes'],
    equal_nan=True
)

validation_df['Consolidated_Net_Income_valid'] = np.isclose(
    profil_and_loss['CONSOLIDATED NET INCOME'],
    profil_and_loss['Net income from continuing operations']
    + profil_and_loss['Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest'],
    equal_nan=True
)

validation_df['Shareowners_Income_valid'] = np.isclose(
    profil_and_loss['NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY'],
    profil_and_loss['CONSOLIDATED NET INCOME']
    - profil_and_loss['Less: Net income attributable to noncontrolling interests'],
    equal_nan=True
)

# Overall validation
validation_cols = validation_df.columns.drop('Financial Year')

validation_df['All_Valid'] = validation_df[validation_cols].all(axis=1)

In [185]:
validation_df[validation_df["All_Valid"] == False]

Empty DataFrame
Columns: [Financial Year, Gross_Profit_valid, Operating_Income_valid, Income_before_taxes_valid, Continuing_Operations_valid, Consolidated_Net_Income_valid, Shareowners_Income_valid, All_Valid]
Index: []

In [186]:
profil_and_loss

,Financial Year,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,Interest expense,Equity income (loss) - net,Other income (loss) - net,Income before income taxes,Income taxes,Net income from continuing operations,"Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",CONSOLIDATED NET INCOME,Less: Net income attributable to noncontrolling interests,NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY
0,FY '09,30990,11088,19902,11358,313,8231,249,355,781,40,8946,2040,6906,0,6906,82,6824
1,FY '10,35119,12693,22426,13194,819,8413,317,733,1025,5185,14207,2370,11837,0,11837,50,11787
2,FY '11,46542,18215,28327,17422,732,10173,483,417,690,529,11458,2812,8646,0,8646,62,8584
3,FY '12,48017,19053,28964,17738,447,10779,471,397,819,137,11809,2723,9086,0,9086,67,9019
4,FY '13,46854,18421,28433,17310,895,10228,534,463,602,576,11477,2851,8626,0,8626,42,8584
5,FY '14,45998,17889,28109,17218,1183,9708,594,483,769,-1263,9325,2201,7124,0,7124,26,7098
6,FY '15,44294,17482,26812,16427,1657,8728,613,856,489,631,9605,2239,7366,0,7366,15,7351
7,FY '16,41863,16465,25398,15262,1510,8626,642,733,835,-1234,8136,1586,6550,0,6550,23,6527
8,FY '17,35410,13255,22155,12654,1902,7599,677,841,1071,-1764,6742,5560,1182,101,1283,35,1248
9,FY '18,31856,11770,20086,10307,1079,8700,682,919,1008,-1121,8350,1623,6727,-251,6476,42,6434

In [187]:
profil_and_loss.to_csv("data/cola_profile_loss_cleaned.csv", index=False)