In [1]:
import pandas as pd

In [2]:
concert_data = pd.read_csv("data/my_file.csv")
concert_data

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [3]:
concert_data.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='str')

In [4]:
concert_data.columns.tolist()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [5]:
concert_data = concert_data.rename(
    columns={
        "Actual\xa0gross": "Actual gross",
        "Adjusted\xa0gross (in 2022 dollars)": "Adjusted gross (in 2022 dollars)",
    }
)

In [6]:
concert_data = concert_data[
    [
        "Rank",
        "Peak",
        "All Time Peak",
        "Actual gross",
        "Adjusted gross (in 2022 dollars)",
        "Artist",
        "Tour title",
        "Year(s)",
        "Shows",
        "Average gross",
    ]
]

In [7]:
concert_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      str
 2   All Time Peak                     6 non-null      str
 3   Actual gross                      20 non-null     str
 4   Adjusted gross (in 2022 dollars)  20 non-null     str
 5   Artist                            20 non-null     str
 6   Tour title                        20 non-null     str
 7   Year(s)                           20 non-null     str
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     str
dtypes: int64(2), str(8)
memory usage: 1.7 KB

In [8]:
concert_data.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571"
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571"
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294"
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795"
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173"

In [9]:
concert_data["Peak"] = pd.to_numeric(
    concert_data["Peak"]
    .astype(str)
    .replace("\[([^\]]+)\]", "", regex=True)
    .astype("Int64")
)

concert_data["All Time Peak"] = pd.to_numeric(
    concert_data["All Time Peak"]
    .astype(str)
    .replace("\[([^\]]+)\]", "", regex=True)
    .astype("Int64")
)

concert_data["Actual gross"] = pd.to_numeric(
    concert_data["Actual gross"]
    .astype(str)
    .str.replace("$", "")
    .str.replace(",", "")
    .str.replace("\[([^\]]+)\]", "", regex=True)
    .astype(float)
)

concert_data["Adjusted gross (in 2022 dollars)"] = pd.to_numeric(
    concert_data["Adjusted gross (in 2022 dollars)"]
    .astype(str)
    .str.replace("$", "")
    .str.replace(",", "")
    .str.replace("\[([^\]]+)\]", "", regex=True)
    .astype(float)
)

concert_data["Artist"] = concert_data["Artist"].str.strip().str.upper()


concert_data["Tour title"] = (
    concert_data["Tour title"]
    .str.strip()
    .replace("^\[[^\]]+\]|\[[^\]]+\]$", "", regex=True)
    .str.replace("[^a-zA-Z0-9\s]", "", regex=True)
    .str.title()
)


concert_data["Start year"] = (
    concert_data["Year(s)"].astype(str).str.extract(r"(^\d+)")[0].astype("Int64")
)

concert_data["End year"] = (
    concert_data["Year(s)"].astype(str).str.extract(r"(\d+$)")[0].astype("Int64")
)

concert_data["Tour duration"] = concert_data["End year"] - concert_data["Start year"] + 1
concert_data = concert_data.drop("Year(s)", axis=1)

concert_data["Average gross"] = pd.to_numeric(
    concert_data["Average gross"]
    .astype(str)
    .str.replace("$", "")
    .str.replace(",", "")
    .str.replace("\[([^\]]+)\]", "", regex=True)
    .astype(float)
)

In [10]:
concert_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      Int64
 2   All Time Peak                     6 non-null      Int64
 3   Actual gross                      20 non-null     float64
 4   Adjusted gross (in 2022 dollars)  20 non-null     float64
 5   Artist                            20 non-null     str
 6   Tour title                        20 non-null     str
 7   Shows                             20 non-null     int64
 8   Average gross                     20 non-null     float64
 9   Start year                        20 non-null     Int64
 10  End year                          20 non-null     Int64
 11  Tour duration                     20 non-null     Int64
dtypes: Int64(5), float64(3), int64(2), str(2)
memory usage: 2.1 KB

In [11]:
concert_data

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Start year,End year,Tour duration
0,1,1,2,780000000.0,780000000.0,TAYLOR SWIFT,The Eras Tour,56,13928571.0,2023,2024,2
1,2,1,7,579800000.0,579800000.0,BEYONCÉ,Renaissance World Tour,56,10353571.0,2023,2023,1
2,3,1,2,411000000.0,560622615.0,MADONNA,Sticky Sweet Tour 4,85,4835294.0,2008,2009,2
3,4,2,10,397300000.0,454751555.0,PINK,Beautiful Trauma World Tour,156,2546795.0,2018,2019,2
4,5,2,<NA>,345675146.0,402844849.0,TAYLOR SWIFT,Reputation Stadium Tour,53,6522173.0,2018,2018,1
5,6,2,10,305158363.0,388978496.0,MADONNA,The Mdna Tour,88,3467709.0,2012,2012,1
6,7,2,<NA>,280000000.0,381932682.0,CELINE DION,Taking Chances World Tour,131,2137405.0,2008,2009,2
7,7,<NA>,<NA>,257600000.0,257600000.0,PINK,Summer Carnival,41,6282927.0,2023,2024,2
8,9,<NA>,<NA>,256084556.0,312258401.0,BEYONCÉ,The Formation World Tour,49,5226215.0,2016,2016,1
9,10,<NA>,<NA>,250400000.0,309141878.0,TAYLOR SWIFT,The 1989 World Tour,85,2945882.0,2015,2015,1
10,11,<NA>,<NA>,229100000.0,283202896.0,BEYONCÉ,The Mrs Carter Show World Tour,132,1735606.0,2013,2014,2
11,12,<NA>,14,227400000.0,295301479.0,LADY GAGA,The Monster Ball Tour,203,1118227.0,2009,2011,3
12,13,<NA>,<NA>,204000000.0,251856802.0,KATY PERRY,Prismatic World Tour,151,1350993.0,2014,2015,2
13,14,1,<NA>,200000000.0,299676265.0,CHER,Living Proof The Farewell Tour 21,325,615385.0,2002,2005,4
14,15,2,<NA>,194000000.0,281617035.0,MADONNA,Confessions Tour,60,3233333.0,2006,2006,1
15,16,<NA>,<NA>,184000000.0,227452347.0,PINK,The Truth About Love Tour,142,1295775.0,2013,2014,2
16,17,<NA>,<NA>,170000000.0,213568571.0,LADY GAGA,Born This Way Ball,98,1734694.0,2012,2013,2
17,18,<NA>,<NA>,169800000.0,207046755.0,MADONNA,Rebel Heart Tour,82,2070732.0,2015,2016,2
18,19,<NA>,<NA>,167700000.0,204486106.0,ADELE,Adele Live 2016,121,1385950.0,2016,2017,2
19,20,<NA>,<NA>,150000000.0,185423109.0,TAYLOR SWIFT,The Red Tour,86,1744186.0,2013,2014,2

In [12]:
concert_data.isna().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Shows                                0
Average gross                        0
Start year                           0
End year                             0
Tour duration                        0
dtype: int64

In [13]:
concert_data.duplicated().sum()

np.int64(0)

In [14]:
concert_data["Artist"].unique()

<StringArray>
['TAYLOR SWIFT',      'BEYONCÉ',      'MADONNA',         'PINK',
  'CELINE DION',    'LADY GAGA',   'KATY PERRY',         'CHER',
        'ADELE']
Length: 9, dtype: str

In [15]:
concert_data["Tour title"].unique()

<StringArray>
[                   'The Eras Tour ',            'Renaissance World Tour',
              'Sticky  Sweet Tour 4',       'Beautiful Trauma World Tour',
           'Reputation Stadium Tour',                     'The Mdna Tour',
         'Taking Chances World Tour',                  'Summer Carnival ',
          'The Formation World Tour',               'The 1989 World Tour',
    'The Mrs Carter Show World Tour',            'The Monster Ball Tour ',
              'Prismatic World Tour', 'Living Proof The Farewell Tour 21',
                  'Confessions Tour',         'The Truth About Love Tour',
                'Born This Way Ball',                  'Rebel Heart Tour',
                   'Adele Live 2016',                      'The Red Tour']
Length: 20, dtype: str

In [16]:
pd.crosstab(index=concert_data["Tour title"], columns=concert_data["Artist"], margins=True)

Artist,ADELE,BEYONCÉ,CELINE DION,CHER,KATY PERRY,LADY GAGA,MADONNA,PINK,TAYLOR SWIFT,All
Tour title,,,,,,,,,,
Adele Live 2016,1,0,0,0,0,0,0,0,0,1
Beautiful Trauma World Tour,0,0,0,0,0,0,0,1,0,1
Born This Way Ball,0,0,0,0,0,1,0,0,0,1
Confessions Tour,0,0,0,0,0,0,1,0,0,1
Living Proof The Farewell Tour 21,0,0,0,1,0,0,0,0,0,1
Prismatic World Tour,0,0,0,0,1,0,0,0,0,1
Rebel Heart Tour,0,0,0,0,0,0,1,0,0,1
Renaissance World Tour,0,1,0,0,0,0,0,0,0,1
Reputation Stadium Tour,0,0,0,0,0,0,0,0,1,1
Sticky Sweet Tour 4,0,0,0,0,0,0,1,0,0,1
Summer Carnival,0,0,0,0,0,0,0,1,0,1
Taking Chances World Tour,0,0,1,0,0,0,0,0,0,1
The 1989 World Tour,0,0,0,0,0,0,0,0,1,1
The Eras Tour,0,0,0,0,0,0,0,0,1,1
The Formation World Tour,0,1,0,0,0,0,0,0,0,1
The Mdna Tour,0,0,0,0,0,0,1,0,0,1
The Monster Ball Tour,0,0,0,0,0,1,0,0,0,1
The Mrs Carter Show World Tour,0,1,0,0,0,0,0,0,0,1
The Red Tour,0,0,0,0,0,0,0,0,1,1
The Truth About Love Tour,0,0,0,0,0,0,0,1,0,1
All,1,3,1,1,1,2,4,3,4,20

In [17]:
concert_data["Peak_missing"] = concert_data["Peak"].isna().astype(int)
concert_data["AllTimePeak_missing"] = concert_data["All Time Peak"].isna().astype(int)

In [18]:
concert_data

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Start year,End year,Tour duration,Peak_missing,AllTimePeak_missing
0,1,1,2,780000000.0,780000000.0,TAYLOR SWIFT,The Eras Tour,56,13928571.0,2023,2024,2,0,0
1,2,1,7,579800000.0,579800000.0,BEYONCÉ,Renaissance World Tour,56,10353571.0,2023,2023,1,0,0
2,3,1,2,411000000.0,560622615.0,MADONNA,Sticky Sweet Tour 4,85,4835294.0,2008,2009,2,0,0
3,4,2,10,397300000.0,454751555.0,PINK,Beautiful Trauma World Tour,156,2546795.0,2018,2019,2,0,0
4,5,2,<NA>,345675146.0,402844849.0,TAYLOR SWIFT,Reputation Stadium Tour,53,6522173.0,2018,2018,1,0,1
5,6,2,10,305158363.0,388978496.0,MADONNA,The Mdna Tour,88,3467709.0,2012,2012,1,0,0
6,7,2,<NA>,280000000.0,381932682.0,CELINE DION,Taking Chances World Tour,131,2137405.0,2008,2009,2,0,1
7,7,<NA>,<NA>,257600000.0,257600000.0,PINK,Summer Carnival,41,6282927.0,2023,2024,2,1,1
8,9,<NA>,<NA>,256084556.0,312258401.0,BEYONCÉ,The Formation World Tour,49,5226215.0,2016,2016,1,1,1
9,10,<NA>,<NA>,250400000.0,309141878.0,TAYLOR SWIFT,The 1989 World Tour,85,2945882.0,2015,2015,1,1,1
10,11,<NA>,<NA>,229100000.0,283202896.0,BEYONCÉ,The Mrs Carter Show World Tour,132,1735606.0,2013,2014,2,1,1
11,12,<NA>,14,227400000.0,295301479.0,LADY GAGA,The Monster Ball Tour,203,1118227.0,2009,2011,3,1,0
12,13,<NA>,<NA>,204000000.0,251856802.0,KATY PERRY,Prismatic World Tour,151,1350993.0,2014,2015,2,1,1
13,14,1,<NA>,200000000.0,299676265.0,CHER,Living Proof The Farewell Tour 21,325,615385.0,2002,2005,4,0,1
14,15,2,<NA>,194000000.0,281617035.0,MADONNA,Confessions Tour,60,3233333.0,2006,2006,1,0,1
15,16,<NA>,<NA>,184000000.0,227452347.0,PINK,The Truth About Love Tour,142,1295775.0,2013,2014,2,1,1
16,17,<NA>,<NA>,170000000.0,213568571.0,LADY GAGA,Born This Way Ball,98,1734694.0,2012,2013,2,1,1
17,18,<NA>,<NA>,169800000.0,207046755.0,MADONNA,Rebel Heart Tour,82,2070732.0,2015,2016,2,1,1
18,19,<NA>,<NA>,167700000.0,204486106.0,ADELE,Adele Live 2016,121,1385950.0,2016,2017,2,1,1
19,20,<NA>,<NA>,150000000.0,185423109.0,TAYLOR SWIFT,The Red Tour,86,1744186.0,2013,2014,2,1,1

In [19]:
concert_data.to_csv("concert_data.csv", index=False)

In [20]:
concert_data.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Shows',
       'Average gross', 'Start year', 'End year', 'Tour duration',
       'Peak_missing', 'AllTimePeak_missing'],
      dtype='str')