# Task 2
## Create 3 DataFrames using Dictionaries

---

In [1]:
import pandas as pd

## 1. DataFrame 1

In [2]:
student_data = {
    "USN" : [101, 102, 103, 104, 105],
    "Name" : ["Derin", "Girish", "Monish", "Deena", "Aditya"],
    "Age" : [22, 22, 21, 23, 21]
}
student_data

{'USN': [101, 102, 103, 104, 105],
 'Name': ['Derin', 'Girish', 'Monish', 'Deena', 'Aditya'],
 'Age': [22, 22, 21, 23, 21]}

In [3]:
student_data_frame = pd.DataFrame(data=student_data)
student_data_frame

   USN    Name  Age
0  101   Derin   22
1  102  Girish   22
2  103  Monish   21
3  104   Deena   23
4  105  Aditya   21

---

## 2. DatFrame 2

In [4]:
employee_data = [
    {"Emp_ID" : 101, "Name" : "Derin", "Salary" : 75000},
    {"Emp_ID" : 102, "Name" : "Girish", "Salary" : 71000},
    {"Emp_ID" : 103, "Name" : "Adarsh", "Salary" : 45000},
    {"Emp_ID" : 104, "Name" : "Nandha", "Salary" : 97000},
    {"Emp_ID" : 105, "Name" : "Yeswanth", "Salary" : 24000},
]
employee_data

[{'Emp_ID': 101, 'Name': 'Derin', 'Salary': 75000},
 {'Emp_ID': 102, 'Name': 'Girish', 'Salary': 71000},
 {'Emp_ID': 103, 'Name': 'Adarsh', 'Salary': 45000},
 {'Emp_ID': 104, 'Name': 'Nandha', 'Salary': 97000},
 {'Emp_ID': 105, 'Name': 'Yeswanth', 'Salary': 24000}]

In [5]:
employee_data_frame = pd.DataFrame(data=employee_data)
employee_data_frame

   Emp_ID      Name  Salary
0     101     Derin   75000
1     102    Girish   71000
2     103    Adarsh   45000
3     104    Nandha   97000
4     105  Yeswanth   24000

---

## 3. DataFrame 3

In [6]:
product_data = {
    "P_101" : {"Product Name" : "Laptop", "Price" : 75000},
    "P_102" : {"Product Name" : "Mobile", "Price" : 20000},
    "P_103" : {"Product Name" : "Tablet", "Price" : 38000},
}
product_data

{'P_101': {'Product Name': 'Laptop', 'Price': 75000},
 'P_102': {'Product Name': 'Mobile', 'Price': 20000},
 'P_103': {'Product Name': 'Tablet', 'Price': 38000}}

In [7]:
product_data_frame = pd.DataFrame.from_dict(data=product_data, orient='index')
product_data_frame

      Product Name  Price
P_101       Laptop  75000
P_102       Mobile  20000
P_103       Tablet  38000

---