# DATA PREPROCESSING/DATA PREPARATION

1. Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype
2. Data Transformation

- If data is CONTINUOUS = Standard Scaler, MinMaxScaIer, Robust Scaler
- If data is DISCRETE = Label Encoder, One hot Encoder

### 1. Import Necssay Libraries

In [654]:
import pandas as pd

### 2. Import Dataset

In [655]:
weather_data = pd.read_csv("assets/environmental_data.csv")

In [656]:
weather_data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

### 3. Data Understanding

#### 3.1 Peform Initial Analysis on the data

In [657]:
weather_data.shape

(158, 10)

In [658]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [659]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C            str
Month             str
Day             int64
Year            int64
Temp            int64
Weather           str
dtype: object

In [660]:
weather_data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [661]:
weather_data.describe(include="all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [662]:
print(f"Count of Unique Class in Weather: {weather_data.Weather.nunique()}")
print(f"List of Unique Class in Weather: {weather_data.Weather.unique().tolist()}")
print(f"Value Count of Unique Class in Weather: {weather_data.Weather.value_counts(dropna=False)}")

Count of Unique Class in Weather: 3
List of Unique Class in Weather: ['S', 'C', 'PS', nan]
Value Count of Unique Class in Weather: Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

### 4. Data Preparation

#### 4.1 - Stage 1 - Data Clearning - drop, fillna with mean, median, mode Imputaion, changing dtypes

#### Note:
1. Drop the NaN if required (with respect to row or column)
2. Do mean, median and mode Inputatino if possible or require
3. Repeate the the step 1 an 2 to remoe all teh null values 
4. Last Step only need to change the Data Type

In [663]:
weather_data.head(10)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S
5           6   28.0      NaN  14.9     66     5    6  2010    66       C
6           7   23.0    299.0   8.6     65     5    7  2010    65      PS
7           8   19.0     99.0  13.8     59     5    8  2010    59       C
8           9    8.0     19.0  20.1     61     5    9  2010    61      PS
9          10    NaN    194.0   8.6     69     5   10  2010    69       S

In [664]:
weather_data.drop(labels=["Unnamed: 0", "Temp C"], axis=1, inplace=True)

> We Removed Unwanted Columns - Unnamed: 0, Temp C

In [665]:
weather_data.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

In [666]:
weather_data.shape

(158, 8)

In [667]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [668]:
print(f"Percentag of NaN Data in Ozon Feature: {(38/158)*100:.3f}%")

Percentag of NaN Data in Ozon Feature: 24.051%

#### 4P 1. Droping the "**Ozone**" Column, as 25% of the data is **NaN**

> As you working in the company
> - If you working under a Team Leader- Inform you Team Leader that the Ozon Featues have 25% of the data is NaN, Shall i drop the Feature or not (decide according to this decion)
> - If you're a Team Leader - Ask to the client or higher authority about this 

- If possible - try to get the data without any of the null data

- Here i am decided to delete the entire column

In [669]:
del weather_data["Ozone"]

In [670]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [671]:
print(f"Percentag of NaN Data in Weather: {(3/158)*100:.3f}%")

Percentag of NaN Data in Weather: 1.899%

> Since Weather have only 3 NaN data drop those three records

In [672]:
weather_data.dropna(subset=["Weather"], inplace=True)

In [673]:
weather_data.isna().sum()

Solar.R    6
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [674]:
print(f"Percentag of NaN Data in Solar.R Feature: {(7/158)*100:.3f}%")

Percentag of NaN Data in Solar.R Feature: 4.430%

In [675]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

- Here what i am planning is here actually i have only three class in output feature (Weather)
    - One option is with respect to the output class calcuate the average Solar.R value and fill with that
        - S (sunny) - calcuate the average of the all teh Solar.R whose ouput Weathere is S (sunny) and same do for C (cloudy) and PS (Partially Sunny)

---

```python
weather_data.groupby("Weather")["Solar.R"].transform(lambda x : x.fillna(x.mean().round()))
```


To reinforce your trace, here is a quick summary confirming your points:
1. Group by Weather: It segments the dataset into unique classes (S, C, PS).
2. Calculate & Round Mean: For each individual class, it calculates the average of the valid Solar.R values and rounds it.
3. Row-by-Row Fill: It checks the rows, finds the NaN values, looks at which weather class that row belongs to, and fills it with that specific group's rounded mean.
You have completely mastered how .groupby().transform() operates under the hood!

---

In [676]:
weather_data["Solar.R"] = weather_data.groupby("Weather", dropna=False)["Solar.R"].transform(lambda x : x.fillna(x.mean().round()))

In [677]:
weather_data[weather_data["Solar.R"].isna()]

Empty DataFrame
Columns: [Solar.R, Wind, Month, Day, Year, Temp, Weather]
Index: []

In [678]:
weather_data.shape

(155, 7)

In [679]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month          str
Day          int64
Year         int64
Temp         int64
Weather        str
dtype: object

In [680]:
weather_data["Month"].unique()

<StringArray>
['5', 'May', '6', '7', '8', '9']
Length: 6, dtype: str

In [681]:
weather_data[weather_data["Month"] == "May"]

    Solar.R  Wind Month  Day  Year  Temp Weather
23     92.0  12.0   May   24  2010    61       C

In [682]:

weather_data.loc[weather_data["Month"] == "May", "Month"] = "5" # Recomended

# or 

# weather_data["Month"] = weather_data["Month"].replace(to_replace="May", value=5)

In [683]:
weather_data[weather_data["Month"] == "May"]

Empty DataFrame
Columns: [Solar.R, Wind, Month, Day, Year, Temp, Weather]
Index: []

In [684]:
weather_data.Month.unique()

<StringArray>
['5', '6', '7', '8', '9']
Length: 5, dtype: str

In [685]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month          str
Day          int64
Year         int64
Temp         int64
Weather        str
dtype: object

In [686]:
weather_data["Month"] =  weather_data["Month"].astype("int")

In [687]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather        str
dtype: object

#### 4.2 - Stage 2 - Data Transformation

- If data is CONTINUOUS = Standard Scaler, MinMaxScaIer, Robust Scaler
- If data is DISCRETE = Label Encoder, One hot Encoder
---


#### How to choose between Label Encoder and One Hot Encoder

1. **For Input feature:**
    - Based on whether it is Parametric or a Non Parametric Model, we will choosing between LE or OHE.
        1. For Parametric Models - better to go with OHE.
        2. For Non-Parametric Models - always go with Label Encoding.
2. **For Output feature:**
    - Always the output feature, it must be Label Encoder.

In [688]:
weather_data.head()

   Solar.R  Wind  Month  Day  Year  Temp Weather
0    190.0   7.4      5    1  2010    67       S
1    118.0   8.0      5    2  2010    72       C
2    149.0  12.6      5    3  2010    74      PS
3    313.0  11.5      5    4  2010    62       S
4    193.0  14.3      5    5  2010    56       S

In [689]:
weather_data_copy_Label_Encoder = weather_data.copy()

#### 4.2.1 Label Encoder

In [690]:
from sklearn.preprocessing import LabelEncoder

In [691]:
le_encoder = LabelEncoder()

weather_data_copy_Label_Encoder["Weather"] = le_encoder.fit_transform(weather_data_copy_Label_Encoder["Weather"])
weather_data_copy_Label_Encoder.head()

   Solar.R  Wind  Month  Day  Year  Temp  Weather
0    190.0   7.4      5    1  2010    67        2
1    118.0   8.0      5    2  2010    72        0
2    149.0  12.6      5    3  2010    74        1
3    313.0  11.5      5    4  2010    62        2
4    193.0  14.3      5    5  2010    56        2

In [692]:
le_mapping = dict(zip(le_encoder.classes_, le_encoder.transform(le_encoder.classes_)))

## Displaying the Encoded Class 
# print(pd.Series(le_mapping))

# or 

print(pd.DataFrame(
    list(le_mapping.items()),
    columns=["Weather", "Encoded_Value"]
))

  Weather  Encoded_Value
0       C              0
1      PS              1
2       S              2

In [693]:
le_encoder.transform(le_encoder.classes_)

array([0, 1, 2])

In [694]:
weather_data_copy_Label_Encoder.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

#### 4.2.2 One Hot Encoder


This can be achieved by using any of the following 2 libraries:

1. Pandas - pd.get_dummies()
2. sklearn - OneHotEncoder()

In [695]:
weather_data_OneHotEncoder_pandas = weather_data.copy()
weather_data_OneHotEncoder_pandas

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [696]:
weather_data_OneHotEncoder_pandas = pd.get_dummies(weather_data_OneHotEncoder_pandas, columns=["Weather"], dtype="int")
weather_data_OneHotEncoder_pandas

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [697]:
weather_data_OneHotEncoder_sklearn = weather_data.copy()

In [698]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [699]:
categorical_cols = ["Weather"]
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ], remainder="passthrough"
)

weather_encoded = preprocessor.fit_transform(
    weather_data_OneHotEncoder_sklearn
)
if hasattr(weather_encoded, "toarray"):
    weather_encoded = weather_encoded.toarray()

In [700]:
weather_data_OneHotEncoder_sklearn

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [702]:
import pandas as pd

weather_data_transformed = pd.DataFrame(
    weather_encoded,
    columns=preprocessor.get_feature_names_out(),
    index=weather_data_OneHotEncoder_sklearn.index
)

weather_data_transformed.head()

,cat__Weather_C,cat__Weather_PS,cat__Weather_S,remainder__Solar.R,remainder__Wind,remainder__Month,remainder__Day,remainder__Year,remainder__Temp
0,0.0,0.0,1.0,190.0,7.4,5.0,1.0,2010.0,67.0
1,1.0,0.0,0.0,118.0,8.0,5.0,2.0,2010.0,72.0
2,0.0,1.0,0.0,149.0,12.6,5.0,3.0,2010.0,74.0
3,0.0,0.0,1.0,313.0,11.5,5.0,4.0,2010.0,62.0
4,0.0,0.0,1.0,193.0,14.3,5.0,5.0,2010.0,56.0

In [701]:
weather_data_OneHotEncoder_sklearn

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]