# Advance DAta Analysis

### Top 8 Poweful Fuctions in Python for Deeper Data Analysis
1. Groupby
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del (keyword)

In [2]:
import pandas as pd

### 1. Groupby Function

In [3]:
insurance_data = pd.read_csv("data/insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### 1.1 Perform Initial Analysis

In [4]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
insurance_data.describe(include="all")

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

In [6]:
insurance_data.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='str')

### 1.2 Pull up the average insurance charges based on region

In [7]:
insurance_data["region"].nunique()

4

In [8]:
insurance_data["region"].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [9]:
insurance_data.groupby(by="region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

#### Discrete and Continous Data
- Discrete -> Just Countable / Can't be segmented
- Continous -> Mesurable / Have units / Can also be segemented

---

**Discrete data** and **Continuous data** are two types of **numerical data** in statistics and data analysis.

Here's the difference:

| Feature         | Discrete Data                   | Continuous Data             |
| --------------- | ------------------------------- | --------------------------- |
| **Definition**  | Countable values                | Measurable values           |
| **Values**      | Specific, separate values       | Any value within a range    |
| **Decimals?**   | Usually no                      | Yes                         |
| **Obtained by** | Counting                        | Measuring                   |
| **Examples**    | Number of students, cars, books | Height, weight, temperature |

#### 1. Discrete Data

Discrete data consists of **distinct/countable values**.

You **count** discrete data.

##### Examples:

* Number of students in a class → 40, 41, 42
* Number of employees → 10, 15
* Number of calls received
* Number of children in a family

You cannot have:

* 3.5 students ❌
* 2.7 cars ❌

So these are **whole-number counts**.

##### Example in Python:

```python id="u4t1x5"
students = [30, 25, 40, 35]
```


#### 2. Continuous Data

Continuous data can take **any value within a range**.

You **measure** continuous data.

##### Examples:

* Height → 170.2 cm
* Weight → 65.8 kg
* Salary → 55000.75
* Temperature → 36.7°C
* Time taken → 2.35 sec

These can have decimal values.

##### Example in Python:

```python id="g15y7y"
height = [165.5, 170.2, 168.9]
```

---

- In our dataset 
    - age - we ca segement as 1.5 years and have "years" as unit - Continious Data
    - sex - We can able to count num. of male and female - Discrete Data
    - smoker - We can able to count num. of yes and no - Discrete Data
    - children - we can't able to count the children as 1.5 children and all, so it's also countable - Discrete Data
    - region - we can able to count number of region are there - Discrete Data
    - bmi - not countable and having unit - Continious Data
    - charges - not countable and having unit - continious Data

In [10]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

- Inside groupby() → usually categorical/discrete grouping columns
- Outside groupby() → usually continuous columns for calculations 
- -> groupby("inner")["outer"]

### 1.3 Pull up the average insurance  charges based on region and sex

In [24]:
pd.DataFrame(insurance_data.groupby(by=["region", "sex"])["charges"].mean().round(2))

                   charges
region    sex
northeast female  12953.20
          male    13854.01
northwest female  12479.87
          male    12354.12
southeast female  13499.67
          male    15879.62
southwest female  11274.41
          male    13412.88

including bmi with the above groupby

In [25]:
pd.DataFrame(insurance_data.groupby(by=["region", "sex"])[["charges", "bmi"]].mean().round(2))

                   charges    bmi
region    sex
northeast female  12953.20  29.32
          male    13854.01  29.02
northwest female  12479.87  29.28
          male    12354.12  29.12
southeast female  13499.67  32.67
          male    15879.62  33.99
southwest female  11274.41  30.06
          male    13412.88  31.13

### 2. Pivot Table

- Presentable comparing two categorical features with one continious data
- value -> should need to be continious data

##### 1.2 Pull up the average insurance charges based on region

In [30]:
pd.pivot_table(data=insurance_data, values="charges", index="region").round(2)

            charges
region
northeast  13406.38
northwest  12417.58
southeast  14735.41
southwest  12346.94

##### 2.3 Pull up the average insurance  charges based on region and sex

In [32]:
pd.pivot_table(data=insurance_data, values="charges", index="region", columns="sex").round(2)

sex          female      male
region
northeast  12953.20  13854.01
northwest  12479.87  12354.12
southeast  13499.67  15879.62
southwest  11274.41  13412.88

In [33]:
pd.pivot_table(
    data=insurance_data, values="charges", index="region", columns=["sex", "children"]
).round(2)

sex          female                                                    \
children          0         1         2         3         4         5
region
northeast   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
northwest  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
southeast  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
southwest  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65

sex            male
children          0         1         2         3         4         5
region
northeast  13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest   9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast  13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest  13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

### 3. Aggregate

In [35]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#### 3.1 Find out the average insurance charges based on region

In [45]:
## This is only by using groupby function
insurance_data.groupby(by="region")["charges"].mean().sort_values(), round(2)

(region
 southwest    12346.937377
 northwest    12417.575374
 northeast    13406.384516
 southeast    14735.411438
 Name: charges, dtype: float64,
 2)

In [44]:
insurance_data.groupby(by="region")["charges"].agg(func=["mean", "min", "max", "sum"]).round(2)

               mean      min       max         sum
region
northeast  13406.38  1694.80  58571.07  4343668.58
northwest  12417.58  1621.34  60021.40  4035712.00
southeast  14735.41  1121.87  63770.43  5363689.76
southwest  12346.94  1241.56  52590.83  4012754.65

#### 3.2 Find out the average insurance charges based on region

In [51]:
insurance_data.groupby(by=["region", "sex"])[["charges"]].agg(func=["mean", "min", "max", "sum"]).round(2)

                   charges
                      mean      min       max         sum
region    sex
northeast female  12953.20  2196.47  58571.07  2085465.71
          male    13854.01  1694.80  48549.18  2258202.88
northwest female  12479.87  2117.34  55135.40  2046698.75
          male    12354.12  1621.34  60021.40  1989013.25
southeast female  13499.67  1607.51  63770.43  2362442.12
          male    15879.62  1121.87  62592.87  3001247.65
southwest female  11274.41  1727.78  48824.45  1826454.62
          male    13412.88  1241.56  52590.83  2186300.02

### 4. Cross Tab

crosstab() in pandas is used to count the frequency (occurrence) between two or more categorical/discrete variables.

In [52]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#### 4.1 How many smokers and non-smoker based on region

In [55]:
pd.crosstab(index=insurance_data["region"], columns=insurance_data["smoker"])

smoker      no  yes
region
northeast  257   67
northwest  267   58
southeast  273   91
southwest  267   58

In [ ]:
pd.crosstab(
    index=insurance_data["region"], columns=insurance_data["smoker"], margins=True
)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [60]:
pd.crosstab(index=[insurance_data["region"], insurance_data["sex"]], columns=insurance_data["smoker"], margins=True)

smoker              no  yes   All
region    sex
northeast female   132   29   161
          male     125   38   163
northwest female   135   29   164
          male     132   29   161
southeast female   139   36   175
          male     134   55   189
southwest female   141   21   162
          male     126   37   163
All               1064  274  1338

In [62]:
pd.crosstab(index=insurance_data['region'] , columns=[insurance_data["smoker"], insurance_data['sex']], margins=True)

smoker        no         yes        All
sex       female male female male
region
northeast    132  125     29   38   324
northwest    135  132     29   29   325
southeast    139  134     36   55   364
southwest    141  126     21   37   325
All          547  517    115  159  1338

### 5. concat

In [71]:
sales_data_2017 = pd.read_csv("data/Sales Transactions-2017.csv")
sales_data_2018 = pd.read_csv("data/Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv("data/Sales Transactions-2019.csv")
sales_data_edited = pd.read_csv("data/Sales-Transactions-Edited.csv")

In [67]:
sales_data_2017

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [68]:
sales_data_2018

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [75]:
sales_data_2019

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [79]:
sales_full_data = pd.concat(objs=[sales_data_2017, sales_data_2018, sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [80]:
sales_full_data.dtypes

Date              str
Voucher           str
Party             str
Product           str
Qty               str
Rate              str
Gross             str
Disc              str
Voucher Amount    str
dtype: object

In [81]:
sales_full_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [83]:
sales_full_data.duplicated().sum()

np.int64(14582)

In [84]:
sales_full_data[sales_full_data.duplicated()]

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
14,NaN,NaN,#NAME?,NaN,NaN,NaN,NaN,NaN,NaN
17,,,dummy entry,,,,,,
39,NaN,NaN,#NAME?,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,#NAME?,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,#NAME?,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19143,NaN,NaN,ET,NaN,NaN,NaN,NaN,NaN,NaN
19162,,,vinayaka sweets-kot,,,,,,
19163,,,hagunta,,,,,,
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
sales_full_data[sales_full_data.isna().all(axis=1)]

      Date Voucher Party Product  Qty Rate Gross Disc Voucher Amount
47286  NaN     NaN   NaN     NaN  NaN  NaN   NaN  NaN            NaN
47287  NaN     NaN   NaN     NaN  NaN  NaN   NaN  NaN            NaN
44736  NaN     NaN   NaN     NaN  NaN  NaN   NaN  NaN            NaN
44737  NaN     NaN   NaN     NaN  NaN  NaN   NaN  NaN            NaN
19172  NaN     NaN   NaN     NaN  NaN  NaN   NaN  NaN            NaN
19173  NaN     NaN   NaN     NaN  NaN  NaN   NaN  NaN            NaN

### merge function
- just explore yourself

### 6. Apply

In [102]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

#### 6.1 Create a new column in the same data frame with the name eligiblity criteria where if age > 20, say elibible else not

In [103]:
insurance_data["age"] > 20

0       False
1       False
2        True
3        True
4        True
        ...
1333     True
1334    False
1335    False
1336     True
1337     True
Name: age, Length: 1338, dtype: bool

In [105]:
if insurance_data.age > 20:
    print("Eligible")
else:
    print("Not Eligible")

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [106]:
def get_age(x):
    if x > 20:
        print("Eligible")
    else:
        print("Not Eligible")
        
insurance_data["Eligiblilty Criteria"]=insurance_data.age.apply(get_age)

Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Eligible
Not Eligible
Not Eligible
Not Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Eligible
Not Eligible
Not Eligible
Eligible
Eligible

In [107]:
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligiblilty Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,None
1,18,male,33.770,1,no,southeast,1725.55230,None
2,28,male,33.000,3,no,southeast,4449.46200,None
3,33,male,22.705,0,no,northwest,21984.47061,None
4,32,male,28.880,0,no,northwest,3866.85520,None
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,None
1334,18,female,31.920,0,no,northeast,2205.98080,None
1335,18,female,36.850,0,no,southeast,1629.83350,None
1336,21,female,25.800,0,no,southwest,2007.94500,None
1337,61,female,29.070,0,yes,northwest,29141.36030,None

In [108]:
def get_age(x):
    if x > 20:
        return "Eligible"
    else:
        return "Not Eligible"

In [109]:
insurance_data["Eligiblilty Criteria"]=insurance_data.age.apply(get_age)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligiblilty Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

### 7. lambda Function

- ananomous function
- can take multiple arguments, but only one expression

In [112]:
insurance_data["EC"] = insurance_data.age.apply(lambda x : "Eligible" if x > 20 else "Not Eligible" )
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligiblilty Criteria,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Eligible
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Eligible

### Explore List Comprehension
### Explore lambda - map, filter, query

### 8. Del keyword

In [113]:
del insurance_data["EC"]

In [114]:
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligiblilty Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible