# Pandas Library Deep Dive ( Data Analyst Tool )

- DataFrames, Series, Indexing, Selection
- Data Input/Output
- Data Cleaning Technique
- Handling Missing Data
- Data Visualization with matplotlib, Seaborn, Ploty

## Data Cycle - Data Scientist

1. Business Understaning - What are the benefits for client and me and for what purpose need to solve
2. Data Collection
3. Data Understanding - perform initail analysis
4. Data Preperation - Data Clearning, for ML Models, etc

## Chapter 1: Getting & Knowing your Data

#### Some Terminology
1. Insights - just found some information
2. Meaningful Insights - just found some information, which is helpful to take some descisions

#### Some Step to follow
1. Name the data by understanding the data

In [3]:
import pandas as pd

In [2]:
order_details = pd.read_csv(filepath_or_buffer="data/data.tsv.txt", sep="\t")

## or

# pd.read_table(filepath_or_buffer="data/data.tsv.txt")

order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 1.1 Perform Initial Analysis on the Data

1. Function - ()
2. Attribute

In [3]:
order_details.shape

(4622, 5)

#### Terminology Alert
- Rows - Observation/Record
- Columns - Features/Parameters

In [4]:
order_details.isnull().sum() ## Chain of functions / chain of commands

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [5]:
## For my Undersanding ( not in course )
## I have exported the choice_description feature/parameter to understand it

# code 👇
# order_details["choice_description"].to_csv(path_or_buf="data/choice_descript.txt", header=False, index=True)

In [6]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [7]:
order_details.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [8]:
order_details.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

👆 Here of the order_id and quantity -> number related operation perfored, in the otherhand item_name, choice_description, item_price -> String related operation performed

In [9]:
## For my Undersanding ( not in course )
## I have tried to find the average of the quantity

# code 👇

# sum = 0
# for i in order_details["quantity"]:
#     sum += i
# print(sum/4622)

### 1.2 Find out the items sold in the Restaurant

In [10]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [11]:
order_details["item_name"]

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: str

In [12]:
order_details["item_name"].unique()

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos',
                    'Chicken Soft Tacos',
                       'Chicken Burrito',
                           'Canned Soda',
                      'Barbacoa Burrito',
                      'Carnitas Burrito',
                         'Carnitas Bowl',
                         'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
                         'Barbacoa Bowl',
                                 'Chips',
                    'Chicken Salad Bowl',
                            'Steak Bowl',
                   'Barbacoa Soft Tacos',
                        'Veggie Burrito',
                           'Veggie Bowl',
                    'Steak Crispy Tacos',
   'Chips and Tomatillo Red Chili Salsa',
                 'Barbacoa Crispy Tacos',
                     'Veggie Salad Bowl',
    'Chips and Roasted Chili-Corn Salsa',
    'Chips and Roasted Chili Corn Salsa',
                   'Carnitas Soft Tacos',
                         'Chicken Salad',
                     'Canned Soft Drink',
                      'Steak Salad Bowl',
                     '6 Pack Soft Drink',
   'Chips and Tomatillo-Red Chili Salsa',
                                  'Bowl',
                               'Burrito',
                          'Crispy Tacos',
                 'Carnitas Crispy Tacos',
                           'Steak Salad',
     'Chips and Mild Fresh Tomato Salsa',
                     'Veggie Soft Tacos',
                   'Carnitas Salad Bowl',
                   'Barbacoa Salad Bowl',
                                 'Salad',
                   'Veggie Crispy Tacos',
                          'Veggie Salad',
                        'Carnitas Salad']
Length: 50, dtype: str

### 1.3 Give me the list of Top 5 Selling Items

In [13]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [14]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [15]:
order_details.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [16]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False).head(10)

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

In [17]:
order_details.groupby(by="item_name")["quantity"].max().sort_values(ascending=False)

item_name
Chips and Fresh Tomato Salsa             15
Bottled Water                            10
Side of Chips                             8
Chips and Guacamole                       4
Canned Soft Drink                         4
Canned Soda                               4
Chicken Burrito                           4
Chicken Bowl                              3
Carnitas Bowl                             3
Bowl                                      3
Chips                                     3
Steak Bowl                                3
Steak Burrito                             3
Chips and Tomatillo-Red Chili Salsa       3
Veggie Burrito                            3
Carnitas Crispy Tacos                     2
Carnitas Burrito                          2
6 Pack Soft Drink                         2
Veggie Soft Tacos                         2
Veggie Bowl                               2
Steak Salad Bowl                          2
Nantucket Nectar                          2
Steak Crispy Tacos                        2
Steak Soft Tacos                          2
Chicken Soft Tacos                        2
Chicken Salad Bowl                        2
Barbacoa Crispy Tacos                     2
Chips and Roasted Chili Corn Salsa        2
Chips and Tomatillo Red Chili Salsa       2
Chips and Tomatillo Green Chili Salsa     2
Chips and Tomatillo-Green Chili Salsa     2
Chicken Crispy Tacos                      2
Barbacoa Burrito                          1
Barbacoa Bowl                             1
Carnitas Soft Tacos                       1
Carnitas Salad Bowl                       1
Carnitas Salad                            1
Burrito                                   1
Barbacoa Soft Tacos                       1
Barbacoa Salad Bowl                       1
Chips and Mild Fresh Tomato Salsa         1
Chicken Salad                             1
Crispy Tacos                              1
Chips and Roasted Chili-Corn Salsa        1
Izze                                      1
Salad                                     1
Steak Salad                               1
Veggie Crispy Tacos                       1
Veggie Salad                              1
Veggie Salad Bowl                         1
Name: quantity, dtype: int64

### 1.4 Give me the list of Least 5 Selling Items

In [18]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head(10)

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Steak Salad                          4
Bowl                                 4
Burrito                              6
Carnitas Salad Bowl                  6
Veggie Salad                         6
Name: quantity, dtype: int64

In [19]:
order_details.groupby(by="item_name")["quantity"].max().sort_values().head(10)

item_name
Barbacoa Bowl                         1
Barbacoa Burrito                      1
Barbacoa Soft Tacos                   1
Barbacoa Salad Bowl                   1
Carnitas Salad Bowl                   1
Carnitas Salad                        1
Burrito                               1
Carnitas Soft Tacos                   1
Chips and Mild Fresh Tomato Salsa     1
Chips and Roasted Chili-Corn Salsa    1
Name: quantity, dtype: int64

## Chapter 2 - Data Cleaning

In [20]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [21]:
order_details.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

- Going to clean the "**$**" symbol from teh item_price

In [22]:
order_details["item_price"].str.replace("$", "").float()

AttributeError: 'Series' object has no attribute 'float'

👆 The above error is because, series didn't have attribue called float \
pd.Series.

In [85]:
order_details["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [86]:
## ❌❌❌
## 👇 This didn't satisfy our requirement, so go for next step

order_details["item_price"].replace(to_replace="$", value="")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [87]:
order_details["item_price"] =  order_details["item_price"].str.replace(pat="$", repl="", regex=False).astype(float)

AttributeError: Can only use .str accessor with string values, not floating

In [88]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [89]:
order_details.dtypes

order_id                int64
quantity                int64
item_name                 str
choice_description        str
item_price            float64
dtype: object

In [90]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

## Task
1. Find out the Top 5 Selling Items - Individual Revenue it made
2. Total Revenue of the Top 5 Sold

#### T_1. Find out the Top 5 Selling Items - Individual Revenue it made

In [91]:
print("Top 5 Selling Items - Individual Revenue it made")
pd.DataFrame(order_details.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head())

Top 5 Selling Items - Individual Revenue it made

                     item_price
item_name
Chicken Bowl            7342.73
Chicken Burrito         5575.82
Steak Burrito           3851.43
Steak Bowl              2260.19
Chips and Guacamole     2201.04

#### T_2 Total Revenue of the Top 5 Items Sold

In [92]:
top_5_item_revenue = order_details.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head().sum()
print(f"Total Revenue of the Top 5 Item Sold: {top_5_item_revenue}")

Total Revenue of the Top 5 Item Sold: 21231.21

## Chapter 3 - Pandas Data Structures

1. 1D - Series
2. 2D - DataFrame

In [93]:
pd.Series(data=[1, 2, 5.6, "$ 5.6"])

0        1
1        2
2      5.6
3    $ 5.6
dtype: object

In [94]:
pd.DataFrame(data=[1, 2, 5.6, "$ 5.6"])

       0
0      1
1      2
2    5.6
3  $ 5.6

In [95]:
pd.DataFrame(
    data={
        "USN": [1, 2, 3, 4, 5],
        "Name": ["Derin", "Girish", "Monish", "Gajendran", "Deena"],
        "Tamil": [89, 45, 87, 25, 89],
        "English": [78, 90, 23, 56, 93],
        "Maths": [56, 78, 34, 97, 54],
    }
)

   USN       Name  Tamil  English  Maths
0    1      Derin     89       78     56
1    2     Girish     45       90     78
2    3     Monish     87       23     34
3    4  Gajendran     25       56     97
4    5      Deena     89       93     54

## Task
1. Create a Meaningful Series
2. Create a Meaningful Dataset using Pandas DataFrame with Dict with 5 observation across 6 features

#### T_1 Create a meaningful Series

In [96]:
marks = pd.Series(
    data = [56, 89, 34, 90, 100], 
    index= ["Tamil", "English", "Math", "Science", "Social"]
)
marks

Tamil       56
English     89
Math        34
Science     90
Social     100
dtype: int64

#### T_2 Create a Meaningful Dataset using Pandas DataFrame with Dict with 5 observation across 6 features

In [97]:
Student_Mark_Details = pd.DataFrame(
    {
        "USN": [1, 2, 3, 4, 5],
        "Name": ["Derin", "Girish", "Monish", "Gajendran", "Deena"],
        "Tamil": [89, 45, 87, 25, 89],
        "English": [78, 90, 23, 56, 93],
        "Maths": [56, 78, 34, 97, 54],
        "Science": [89, 32, 80, 34, 56],
    }
)
Student_Mark_Details

   USN       Name  Tamil  English  Maths  Science
0    1      Derin     89       78     56       89
1    2     Girish     45       90     78       32
2    3     Monish     87       23     34       80
3    4  Gajendran     25       56     97       34
4    5      Deena     89       93     54       56

## Chapter 4 - Filtering & Selction & Sorting

In [98]:
euro_2012_data = pd.read_csv("data/Euro_2012_stats_TEAM.csv")
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [99]:
# pd.set_option("display.max_columns", None)
# pd.reset_option("display.max_coulumn")

In [100]:
euro_2012_data.shape

(16, 35)

In [101]:
euro_2012_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='str')

In [102]:
euro_2012_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     str
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     str
 5   % Goals-to-shots            16 non-null     str
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     str
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     str
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), str(5)
memory usage: 4.5 KB

In [103]:
filtered_euro_data =  euro_2012_data[["Team", "Goals", "Red Cards", "Yellow Cards"]] 
## [["Team", "Goals", "Red Cards", "Yellow Cards"]]
## outer square bracket -> for filteration
## inner square bracket -> for fileratiion muliple features

In [104]:
filtered_euro_data

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [105]:
filtered_euro_data["Yellow Cards"]

0      9
1      7
2      4
3      5
4      6
5      4
6      9
7     16
8      5
9      7
10    12
11     6
12     6
13    11
14     7
15     5
Name: Yellow Cards, dtype: int64

##### Other options for column selection are
- loc
- iloc

### 4.1 Stort Teams w.r.t Card

#### Storted Yellow Card Teams

In [106]:
filtered_euro_data.sort_values(by="Yellow Cards", ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
7                 Italy      6          0            16
10             Portugal      6          0            12
13                Spain     12          0            11
0               Croatia      4          0             9
6                Greece      5          1             9
14               Sweden      5          0             7
9                Poland      2          1             7
1        Czech Republic      4          0             7
12               Russia      5          0             6
11  Republic of Ireland      1          1             6
4                France      3          0             6
3               England      5          0             5
8           Netherlands      2          0             5
15              Ukraine      2          0             5
5               Germany     10          0             4
2               Denmark      4          0             4

#### Sort Red Card Team

In [107]:
filtered_euro_data.sort_values(by="Yellow Cards", ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
7                 Italy      6          0            16
10             Portugal      6          0            12
13                Spain     12          0            11
0               Croatia      4          0             9
6                Greece      5          1             9
14               Sweden      5          0             7
9                Poland      2          1             7
1        Czech Republic      4          0             7
12               Russia      5          0             6
11  Republic of Ireland      1          1             6
4                France      3          0             6
3               England      5          0             5
8           Netherlands      2          0             5
15              Ukraine      2          0             5
5               Germany     10          0             4
2               Denmark      4          0             4

#### Sorted Yellow and Red Card w.r.t Decending Order

In [108]:
filtered_euro_data.sort_values(by=["Yellow Cards", "Red Cards"], ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
7                 Italy      6          0            16
10             Portugal      6          0            12
13                Spain     12          0            11
6                Greece      5          1             9
0               Croatia      4          0             9
9                Poland      2          1             7
1        Czech Republic      4          0             7
14               Sweden      5          0             7
11  Republic of Ireland      1          1             6
4                France      3          0             6
12               Russia      5          0             6
3               England      5          0             5
8           Netherlands      2          0             5
15              Ukraine      2          0             5
2               Denmark      4          0             4
5               Germany     10          0             4

## Conditional Filtering

### 4.2 List the Teams which has got Red Cards

#### Pandas Filtering Notes

``` python
euro12[euro12["Goals"] > 5][["Team", "Goals"]]
```

1.  `euro12["Goals"] > 5` → Creates Boolean mask (True/False).
2.  `euro12[mask]` → Filters rows where condition is True.
3.  `[["Team","Goals"]]` → Selects required columns.
4.  Flow: Mask → Filter → Select.
5.  Cleaner version:

``` python
mask = euro12["Goals"] > 5
result = euro12[mask][["Team","Goals"]]
```

In [109]:
## ❌❌❌
## filtered_euro_data["Red Cards"] = 1

👆 The Above code make all the data in red card to "1" so don't do that mistake, be aware of using "=", aware of using "=" and "==".

In [110]:
filtered_euro_data["Red Cards"].unique()

array([0, 1])

In [111]:
filtered_euro_data["Red Cards"] == 1

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

In [112]:
filtered_euro_data[filtered_euro_data["Red Cards"] == 1]

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6

### 4.3 List the teams which got more than 8 Yellow Cards

In [113]:
filtered_euro_data[filtered_euro_data["Yellow Cards"] >= 8].sort_values(
    by="Yellow Cards",ascending=False
)

        Team  Goals  Red Cards  Yellow Cards
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11
0    Croatia      4          0             9
6     Greece      5          1             9

#### Filtering and sorting w.r.t Yellow Card and Red Card

In [114]:
filtered_euro_data[
    (filtered_euro_data["Yellow Cards"] >= 1) | (filtered_euro_data["Red Cards"] >= 1)
].sort_values(by=["Yellow Cards", "Red Cards"], ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
7                 Italy      6          0            16
10             Portugal      6          0            12
13                Spain     12          0            11
6                Greece      5          1             9
0               Croatia      4          0             9
9                Poland      2          1             7
1        Czech Republic      4          0             7
14               Sweden      5          0             7
11  Republic of Ireland      1          1             6
4                France      3          0             6
12               Russia      5          0             6
3               England      5          0             5
8           Netherlands      2          0             5
15              Ukraine      2          0             5
2               Denmark      4          0             4
5               Germany     10          0             4

In [115]:
filtered_euro_data[
    (filtered_euro_data["Yellow Cards"] >= 1) & (filtered_euro_data["Red Cards"] >= 1)
].sort_values(by=["Yellow Cards", "Red Cards"], ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6

In [116]:
filtered_euro_data.to_csv("data/filtered_euro_data.csv")

## Task
1. Find out 5 New Questions along with Script Answers

#### 1. Sorting Questions
##### Performance Ranking
* Which teams scored the **highest goals**?
* Which teams had the **best passing accuracy**?
* Which teams received the **most yellow cards**?
* Which teams conceded the **fewest goals**?
* Top 5 teams with the **highest shooting accuracy**.

#### 2. Filtering Questions
##### Discipline Analysis
* Which teams got **at least 1 red card**?
* Which teams received **more than 10 yellow cards**?
* Teams with **clean sheets AND low fouls**.
##### Attack Performance
* Teams with **Goals > 5**.
* Teams with **Shooting Accuracy > 50%**.
* Teams with **more shots but low conversion**.

#### 3. Selection Questions
Business may not want all 35 columns. \
Questions:
* Show only:
  * Team
  * Goals
  * Passing Accuracy
* Show:
  * Team
  * Yellow Cards
  * Red Cards

#### 4. Slicing Questions
(View only a portion of data)
* Show first 5 teams.
* Show last 3 teams.
* Review rows 5–10 only.
* Inspect selected columns and rows.

# 5. Combined Business Questions

(Real analyst-style questions)

### Coach Questions

* Which teams had **high passing accuracy but low goals**?
* Which disciplined teams performed better?
* Teams with **many shots but poor shooting accuracy**.

### Federation Questions

* Which teams played **aggressively**?

  * High fouls
  * High yellow/red cards

### Performance Questions

* Top attacking teams:

  * High goals
  * High shooting accuracy
  * High shots on target

Example:

```python
euro12[
    (euro12["Goals"] > 5) &
    (euro12["Yellow Cards"] < 10)
][["Team","Goals"]]
```

---

In [117]:
task_euro_2012_data = euro_2012_data

---

In [118]:
pd.DataFrame(task_euro_2012_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     str
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     str
 5   % Goals-to-shots            16 non-null     str
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     str
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     str
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), str(5)
memory usage: 4.5 KB

Empty DataFrame
Columns: []
Index: []

In [119]:
pd.Series(task_euro_2012_data.columns)

0                           Team
1                          Goals
2                Shots on target
3               Shots off target
4              Shooting Accuracy
5               % Goals-to-shots
6     Total shots (inc. Blocked)
7                   Hit Woodwork
8                  Penalty goals
9           Penalties not scored
10                  Headed goals
11                        Passes
12              Passes completed
13              Passing Accuracy
14                       Touches
15                       Crosses
16                      Dribbles
17                 Corners Taken
18                       Tackles
19                    Clearances
20                 Interceptions
21           Clearances off line
22                  Clean Sheets
23                        Blocks
24                Goals conceded
25                    Saves made
26          Saves-to-shots ratio
27                     Fouls Won
28                Fouls Conceded
29                      Offsides
30                  Yellow Cards
31                     Red Cards
32                       Subs on
33                      Subs off
34                  Players Used
dtype: str

## T_1. Sorting Question

#### T_1.1 Which teams scored the highest goals?

In [120]:
task_euro_2012_data[["Team", "Goals"]].sort_values(by="Goals", ascending=False)

                   Team  Goals
13                Spain     12
5               Germany     10
10             Portugal      6
7                 Italy      6
14               Sweden      5
12               Russia      5
3               England      5
6                Greece      5
1        Czech Republic      4
0               Croatia      4
2               Denmark      4
4                France      3
8           Netherlands      2
9                Poland      2
15              Ukraine      2
11  Republic of Ireland      1

#### T_1.2 Which teams had the **best passing accuracy**?

In [121]:
task_euro_2012_data["Passing Accuracy"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Passing Accuracy
Non-Null Count  Dtype
--------------  -----
16 non-null     str
dtypes: str(1)
memory usage: 260.0 bytes

In [122]:
task_euro_2012_data["Passing Accuracy"].describe(include="all")

count        16
unique       15
top       83.9%
freq          2
Name: Passing Accuracy, dtype: object

In [123]:
task_euro_2012_data["Passing Accuracy"] = task_euro_2012_data["Passing Accuracy"].str.replace(pat="%", repl="").astype(float)

In [124]:
task_euro_2012_data["Passing Accuracy"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Passing Accuracy
Non-Null Count  Dtype
--------------  -----
16 non-null     float64
dtypes: float64(1)
memory usage: 260.0 bytes

In [125]:
task_euro_2012_data[["Team", "Passing Accuracy"]].sort_values(by="Passing Accuracy", ascending=False)

                   Team  Passing Accuracy
8           Netherlands              88.7
13                Spain              88.4
5               Germany              87.4
4                France              87.2
7                 Italy              83.9
12               Russia              83.9
2               Denmark              83.3
15              Ukraine              81.7
14               Sweden              80.9
3               England              80.6
9                Poland              80.4
1        Czech Republic              78.1
10             Portugal              77.2
0               Croatia              76.9
6                Greece              76.7
11  Republic of Ireland              71.2

#### T_1.3 Which teams received the **most yellow cards**?

In [126]:
task_euro_2012_data["Yellow Cards"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Yellow Cards
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 260.0 bytes

In [127]:
task_euro_2012_data[["Team", "Yellow Cards"]].sort_values(by="Yellow Cards", ascending=False)

                   Team  Yellow Cards
7                 Italy            16
10             Portugal            12
13                Spain            11
0               Croatia             9
6                Greece             9
14               Sweden             7
9                Poland             7
1        Czech Republic             7
12               Russia             6
11  Republic of Ireland             6
4                France             6
3               England             5
8           Netherlands             5
15              Ukraine             5
5               Germany             4
2               Denmark             4

#### T_1.4 Which teams conceded the **fewest goals**?

In [128]:
task_euro_2012_data["Goals conceded"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Goals conceded
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 260.0 bytes

In [129]:
task_euro_2012_data[["Team", "Goals conceded"]].sort_values(by="Goals conceded")

                   Team  Goals conceded
13                Spain               1
0               Croatia               3
9                Poland               3
3               England               3
12               Russia               3
10             Portugal               4
15              Ukraine               4
2               Denmark               5
4                France               5
8           Netherlands               5
14               Sweden               5
1        Czech Republic               6
5               Germany               6
6                Greece               7
7                 Italy               7
11  Republic of Ireland               9

#### T_1.5 Top 5 teams with the **highest shooting accuracy**.

In [130]:
task_euro_2012_data["Shooting Accuracy"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Shooting Accuracy
Non-Null Count  Dtype
--------------  -----
16 non-null     str
dtypes: str(1)
memory usage: 260.0 bytes

In [131]:
task_euro_2012_data["Shooting Accuracy"] = task_euro_2012_data["Shooting Accuracy"].str.replace(pat="%", repl="").astype(float)

In [132]:
task_euro_2012_data[["Team", "Shooting Accuracy"]].sort_values(by="Shooting Accuracy", ascending=False).head()

       Team  Shooting Accuracy
13    Spain               55.9
0   Croatia               51.9
3   England               50.0
2   Denmark               50.0
5   Germany               47.8

---

## T_2. Filtering Question

### T_2_1 Discipline Analysis

#### T_2_1.1 Which teams got **at least 1 red card**?

In [133]:
task_euro_2012_data["Red Cards"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Red Cards
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 260.0 bytes

In [134]:
task_euro_2012_data[task_euro_2012_data["Red Cards"] >= 1][["Team", "Red Cards"]]

                   Team  Red Cards
6                Greece          1
9                Poland          1
11  Republic of Ireland          1

#### T_2_1.2 Which teams received **more than 10 yellow cards**?

In [135]:
task_euro_2012_data["Yellow Cards"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Yellow Cards
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 260.0 bytes

In [136]:
task_euro_2012_data[task_euro_2012_data["Yellow Cards"] > 10][["Team", "Yellow Cards"]].sort_values(by="Yellow Cards")

        Team  Yellow Cards
13     Spain            11
10  Portugal            12
7      Italy            16

#### T_2_1.3 Teams with **clean sheets AND low fouls**.

In [137]:
task_euro_2012_data["Clean Sheets"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Clean Sheets
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 260.0 bytes

In [138]:
task_euro_2012_data["Fouls Conceded"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Fouls Conceded
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 260.0 bytes

In [139]:
task_euro_2012_data[
    (task_euro_2012_data["Clean Sheets"] > 0)
    & (
        task_euro_2012_data["Fouls Conceded"]
        < task_euro_2012_data["Fouls Conceded"].mean()
    )
][
    [
        "Team",
        "Fouls Conceded",
        "Clean Sheets",
    ]
].sort_values(
    by=["Fouls Conceded", "Clean Sheets"], ascending=[True, False]
)

       Team  Fouls Conceded  Clean Sheets
2   Denmark              38             1
3   England              45             2
6    Greece              48             1
5   Germany              49             1
4    France              51             1
14   Sweden              51             1

### T_2_2 Attack Performance

#### T_2_2.1 Teams with **Goals > 5**.

In [140]:
task_euro_2012_data[task_euro_2012_data["Goals"] > 5][["Team", "Goals"]]

        Team  Goals
5    Germany     10
7      Italy      6
10  Portugal      6
13     Spain     12

#### T_2_2.2 Teams with **Shooting Accuracy > 50%**.

In [141]:
task_euro_2012_data["Shooting Accuracy"].info()

<class 'pandas.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: Shooting Accuracy
Non-Null Count  Dtype
--------------  -----
16 non-null     float64
dtypes: float64(1)
memory usage: 260.0 bytes

In [142]:
task_euro_2012_data["Shooting Accuracy"]

0     51.9
1     41.9
2     50.0
3     50.0
4     37.9
5     47.8
6     30.7
7     43.0
8     25.0
9     39.4
10    34.3
11    36.8
12    22.5
13    55.9
14    47.2
15    21.2
Name: Shooting Accuracy, dtype: float64

In [143]:
task_euro_2012_data[task_euro_2012_data["Shooting Accuracy"] > 50][["Team","Shooting Accuracy"]]

       Team  Shooting Accuracy
0   Croatia               51.9
13    Spain               55.9

#### T_2_2.3 Teams with **more shots but low conversion**.

In [160]:
average_total_shot = task_euro_2012_data["Total shots (inc. Blocked)"].mean()
average_total_shot

np.float64(54.9375)

In [161]:
task_euro_2012_data["shot_to_goal_conversion"] = (task_euro_2012_data["Goals"] / task_euro_2012_data["Total shots (inc. Blocked)"]) * 100

In [163]:
task_euro_2012_data["shot_to_goal_conversion"].mean()

np.float64(9.07580649185947)

In [164]:
task_euro_2012_data[
    (task_euro_2012_data["Total shots (inc. Blocked)"] > average_total_shot)
    & (
        task_euro_2012_data["shot_to_goal_conversion"]
        < task_euro_2012_data["shot_to_goal_conversion"].mean()
    )
][["Team", "Goals", "Total shots (inc. Blocked)", "shot_to_goal_conversion"]]

           Team  Goals  Total shots (inc. Blocked)  shot_to_goal_conversion
4        France      3                          65                 4.615385
7         Italy      6                         110                 5.454545
8   Netherlands      2                          60                 3.333333
10     Portugal      6                          82                 7.317073
12       Russia      5                          59                 8.474576

---

## T_3. Selection Question

#### T_3.1 Show only Team, Goals, Passing Accuracy

In [166]:
task_euro_2012_data[["Team", "Goals", "Passing Accuracy"]]

                   Team  Goals  Passing Accuracy
0               Croatia      4              76.9
1        Czech Republic      4              78.1
2               Denmark      4              83.3
3               England      5              80.6
4                France      3              87.2
5               Germany     10              87.4
6                Greece      5              76.7
7                 Italy      6              83.9
8           Netherlands      2              88.7
9                Poland      2              80.4
10             Portugal      6              77.2
11  Republic of Ireland      1              71.2
12               Russia      5              83.9
13                Spain     12              88.4
14               Sweden      5              80.9
15              Ukraine      2              81.7

#### T_3.1 show Team, Yellow Cards, Red Cards

In [167]:
task_euro_2012_data[["Team", "Yellow Cards", "Red Cards"]]

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

---

## 4. Slicing Questions

#### T_4.1 Show first 5 teams

In [168]:
task_euro_2012_data.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,shot_to_goal_conversion
0,Croatia,4,13,12,51.9,16.0%,32,0,0,0,...,81.3%,41,62,2,9,0,9,9,16,12.500000
1,Czech Republic,4,13,18,41.9,12.9%,39,0,0,0,...,60.1%,53,73,8,7,0,11,11,19,10.256410
2,Denmark,4,10,10,50.0,20.0%,27,1,0,0,...,66.7%,25,38,8,4,0,7,7,15,14.814815
3,England,5,11,18,50.0,17.2%,40,0,0,0,...,88.1%,43,45,6,5,0,11,11,16,12.500000
4,France,3,22,24,37.9,6.5%,65,1,0,0,...,54.6%,36,51,5,6,0,11,11,19,4.615385

#### T_4.2 Show last 3 teams

In [169]:
task_euro_2012_data.tail(3)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,shot_to_goal_conversion
13,Spain,12,42,33,55.9,16.0%,100,0,1,0,...,93.8%,102,83,19,11,0,17,17,18,12.000000
14,Sweden,5,17,19,47.2,13.8%,39,3,0,0,...,61.6%,35,51,7,7,0,9,9,18,12.820513
15,Ukraine,2,7,26,21.2,6.0%,38,0,0,0,...,76.5%,48,31,4,5,0,9,9,18,5.263158

#### T_4.3 Review rows 5 - 10 only

In [170]:
task_euro_2012_data.iloc[5:11]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,shot_to_goal_conversion
5,Germany,10,32,32,47.8,15.6%,80,2,1,0,...,62.6%,63,49,12,4,0,15,15,17,12.500000
6,Greece,5,8,18,30.7,19.2%,32,1,1,1,...,65.1%,67,48,12,9,1,12,12,20,15.625000
7,Italy,6,34,45,43.0,7.5%,110,2,0,0,...,74.1%,101,89,16,16,0,18,18,19,5.454545
8,Netherlands,2,12,36,25.0,4.1%,60,2,0,0,...,70.6%,35,30,3,5,0,7,7,15,3.333333
9,Poland,2,15,23,39.4,5.2%,48,0,0,0,...,66.7%,48,56,3,7,1,7,7,17,4.166667
10,Portugal,6,22,42,34.3,9.3%,82,6,0,0,...,71.5%,73,90,10,12,0,14,14,16,7.317073

#### T_4.4 Inspect Selected Columns and rows

In [175]:
task_euro_2012_data.loc[5:10, ["Goals", "Team"]]

    Goals         Team
5      10      Germany
6       5       Greece
7       6        Italy
8       2  Netherlands
9       2       Poland
10      6     Portugal

---

# More Task there for combined function......

---

## Chapter 5 - How to deal with missing values

In [182]:
proitbridge_emp_data = pd.read_csv("data/Employee_data.csv")
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

# Level 1 of Data Cleaning

### Always Reconmended: I'll call to my client, and check with him if he can give the right data - Great


Incase, client is asking use to perform the Data Cleaning Operations

#### Step 1: Remove Duplicate Entries / Records

In [183]:
## proitbridge_emp_data = proitbridge_emp_data.drop_duplicates()

## for saving if the function have "inplace" function then use it

proitbridge_emp_data.drop_duplicates(inplace=True)

In [184]:
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

#### Step 2: Find out the null entries

In [186]:
proitbridge_emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [188]:
proitbridge_emp_data.shape

(7, 5)

In [189]:
proitbridge_emp_data.dropna(inplace=True)

In [190]:
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [192]:
proitbridge_emp_data.shape

(4, 5)

#### Step 3: Record in a Document
- Client gave totally 7 obervations out of which 3 entries are removed because of those records do not have complete information.

#### Step 4: Get Approval
- Sent this to Client and get the approval to proceed for Model building or Model Training.

In [193]:
proitbridge_emp_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

---

# Level 2 of Data Cleaning

In [125]:
import pandas as pd

In [126]:
# pd.read_csv() 
# CSV file not having multiple sheet

In [127]:
## for using read_exel() function you need to install "openpyxl" library 
## By default read_excel() function will load the first sheet of the excel file
pd.read_excel(io="data/Employee_data.xlsx")

      Name   Age Department   Salary            Join_Date
0   Rajesh  29.0        Ops  60000.0           21-05-2023
1    Nasir  31.0    IT Tech      NaN  2020-11-12 00:00:00
2  Mathiew   NaN    Support  58000.0           15-01-2025
3  Gilbert  29.0        Ops  60000.0           21-05-2021
4    Kevin  28.0    Support  61000.0           30-07-2024
5    Navin  35.0    Support  72000.0           19-08-2023
6      NaN  40.0         IT  64000.0  2022-09-10 00:00:00
7    Nasir  31.0    IT Tech      NaN  2020-11-12 00:00:00

In [128]:
employee_added_details = pd.read_excel(io="data/Employee_data.xlsx", sheet_name="More_Employee_Data")
employee_added_details

             Name   Age Department   Salary            Join_Date
0          Rajesh  29.0        Ops  60000.0           21-05-2023
1           Nasir  31.0    IT Tech  62000.0  2020-12-11 00:00:00
2         Mathiew   NaN    Support  58000.0           15-01-2025
3         Gilbert  29.0        Ops  60000.0           21-05-2021
4           Kevin  28.0    Support  61000.0           30-07-2024
5           Navin  35.0    Support  72000.0           19-08-2023
6             NaN  40.0    IT Tech  64000.0  2022-10-09 00:00:00
7          Roshan  31.0    IT Tech      NaN  2020-12-11 00:00:00
8       Kuppusamy  28.0        Ops      NaN           21-05-2021
9           Ajesh  28.0    Support      NaN           30-07-2024
10           Diya  31.0    IT Tech  63000.0  2020-12-11 00:00:00
11        Mathiew   NaN    Support  58000.0           15-01-2025
12  Jagadheeswari  28.0    IT Tech      NaN                  NaN
13           Mani  28.0        Ops      NaN           21-05-2021

In [129]:
## This is for restructuring the Data formate properly

employee_added_details["Join_Date"] = pd.to_datetime(
    employee_added_details["Join_Date"], dayfirst=True, errors="coerce"
).dt.strftime("%d-%m-%Y")

In [130]:
employee_added_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  11-12-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  09-10-2022
7          Roshan  31.0    IT Tech      NaN  11-12-2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  11-12-2020
11        Mathiew   NaN    Support  58000.0  15-01-2025
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

#### Step 1: Drop Duplicates

In [131]:
employee_added_details.shape

(14, 5)

In [132]:
print(f"Duplicate Record/Observation Count: {employee_added_details.duplicated().sum()}")
employee_added_details.duplicated()

Duplicate Record/Observation Count: 1

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
dtype: bool

In [133]:
employee_added_details.drop_duplicates(inplace=True)

In [134]:
employee_added_details.shape

(13, 5)

👉 1 Record is deleted because of Duplicate Record  \
So From 14 Record to 13 Record

In [135]:
employee_added_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  11-12-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  09-10-2022
7          Roshan  31.0    IT Tech      NaN  11-12-2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  11-12-2020
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

#### Step 2: Identify Null Entries/Observaion

In [136]:
employee_added_details.isnull().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     1
dtype: int64

#### Step 3: Go for best Imputation

In [137]:
employee_added_details[employee_added_details[["Salary"]].isnull().any(axis=1)]

             Name   Age Department  Salary   Join_Date
7          Roshan  31.0    IT Tech     NaN  11-12-2020
8       Kuppusamy  28.0        Ops     NaN  21-05-2021
9           Ajesh  28.0    Support     NaN  30-07-2024
12  Jagadheeswari  28.0    IT Tech     NaN         NaN
13           Mani  28.0        Ops     NaN  21-05-2021

In [138]:
employee_added_details["Department"].unique()

<StringArray>
['Ops', 'IT Tech', 'Support']
Length: 3, dtype: str

### Support Department

In [139]:
employee_added_details[employee_added_details["Department"] == "Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support      NaN  30-07-2024

👆 In the above you can observe that for kevin 28 age 61k salary, so that Ajesh also have age 28 , so he also might eligible for 61k

### IT Tech Department

In [140]:
employee_added_details[employee_added_details["Department"] == "IT Tech"]

             Name   Age Department   Salary   Join_Date
1           Nasir  31.0    IT Tech  62000.0  11-12-2020
6             NaN  40.0    IT Tech  64000.0  09-10-2022
7          Roshan  31.0    IT Tech      NaN  11-12-2020
10           Diya  31.0    IT Tech  63000.0  11-12-2020
12  Jagadheeswari  28.0    IT Tech      NaN         NaN

### Ops Department

In [141]:
employee_added_details[employee_added_details["Department"] == "Ops"]

         Name   Age Department   Salary   Join_Date
0      Rajesh  29.0        Ops  60000.0  21-05-2023
3     Gilbert  29.0        Ops  60000.0  21-05-2021
8   Kuppusamy  28.0        Ops      NaN  21-05-2021
13       Mani  28.0        Ops      NaN  21-05-2021

## Task 
1. Impute the relevant vales in the Salary Column wherevery it is NaN

In [142]:
employee_added_details[(employee_added_details["Department"] == "Support") & (employee_added_details["Salary"].isna())]

    Name   Age Department  Salary   Join_Date
9  Ajesh  28.0    Support     NaN  30-07-2024

In [143]:
employee_added_details.loc[
    (employee_added_details["Department"] == "Support")
    & (employee_added_details["Salary"].isna()), 
    "Salary"
] = 61000

In [144]:
employee_added_details[
    (employee_added_details["Department"] == "Support")
]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support  61000.0  30-07-2024

In [145]:
employee_added_details.loc[(employee_added_details["Department"] == "IT Tech") & (employee_added_details["Salary"].isna()), "Salary"] = 62000

In [146]:
employee_added_details.loc[(employee_added_details["Department"] == "Ops") & (employee_added_details["Salary"].isna()), "Salary"] = 60000

In [147]:
employee_added_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  11-12-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  09-10-2022
7          Roshan  31.0    IT Tech  62000.0  11-12-2020
8       Kuppusamy  28.0        Ops  60000.0  21-05-2021
9           Ajesh  28.0    Support  61000.0  30-07-2024
10           Diya  31.0    IT Tech  63000.0  11-12-2020
12  Jagadheeswari  28.0    IT Tech  62000.0         NaN
13           Mani  28.0        Ops  60000.0  21-05-2021

In [150]:
employee_added_details[employee_added_details["Department"] == "Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support  61000.0  30-07-2024

In [151]:
employee_added_details[employee_added_details["Department"] == "IT Tech"]

             Name   Age Department   Salary   Join_Date
1           Nasir  31.0    IT Tech  62000.0  11-12-2020
6             NaN  40.0    IT Tech  64000.0  09-10-2022
7          Roshan  31.0    IT Tech  62000.0  11-12-2020
10           Diya  31.0    IT Tech  63000.0  11-12-2020
12  Jagadheeswari  28.0    IT Tech  62000.0         NaN

In [152]:
employee_added_details[employee_added_details["Department"] == "Ops"]

         Name   Age Department   Salary   Join_Date
0      Rajesh  29.0        Ops  60000.0  21-05-2023
3     Gilbert  29.0        Ops  60000.0  21-05-2021
8   Kuppusamy  28.0        Ops  60000.0  21-05-2021
13       Mani  28.0        Ops  60000.0  21-05-2021

In [153]:
employee_added_details.isna().sum()

Name          1
Age           1
Department    0
Salary        0
Join_Date     1
dtype: int64

In [154]:
employee_added_details[employee_added_details["Age"].isna()]

      Name  Age Department   Salary   Join_Date
2  Mathiew  NaN    Support  58000.0  15-01-2025

In [155]:
list = [1,2,3,4]
list = list[::-1]
list

[4, 3, 2, 1]

In [159]:
nums = [1,2,3,4,5]
rev = []

for i in range(len(nums)):
    rev.insert(0, nums[i])
    
rev

[5, 4, 3, 2, 1]

In [ ]:
nums = [1, 2, 3, 4, 5]
rev = []