# Python Chapter 4 - Task 2

#### Task 1
Data Cleaning Challenge on Sales Data.

#### Task 2
Merge Function 1 Example

#### Task 3
List Comprehension 2 examples

#### Task 4
Lambda Function 2 examples with Map, Filter, Reduce

# Task 1
### Data Cleaning Challenge on Sales Data.

In [53]:
import pandas as pd

In [54]:
sales_data_2017 = pd.read_csv(filepath_or_buffer="data/Sales Transactions-2017.csv")
sales_data_2018 = pd.read_csv(filepath_or_buffer="data/Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv(filepath_or_buffer="data/Sales Transactions-2019.csv")

In [55]:
# sales_data_2017

In [56]:
# sales_data_2018

In [57]:
# sales_data_2019

In [58]:
full_sales_data = pd.concat(objs=[sales_data_2017, sales_data_2018, sales_data_2019])
full_sales_data.to_csv("data/full_sales_data.csv")
full_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

---

In [59]:
full_sales_data.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN

In [60]:
full_sales_data.tail()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [61]:
full_sales_data.shape

(111206, 9)

In [62]:
full_sales_data.info()

<class 'pandas.DataFrame'>
Index: 111206 entries, 0 to 19175
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            98615 non-null   str
 1   Voucher         98649 non-null   str
 2   Party           111166 non-null  str
 3   Product         98615 non-null   str
 4   Qty             98649 non-null   str
 5   Rate            98648 non-null   str
 6   Gross           98648 non-null   str
 7   Disc            5597 non-null    str
 8   Voucher Amount  27560 non-null   str
dtypes: str(9)
memory usage: 8.5 MB

In [63]:
full_sales_data.describe(include="all")

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

In [64]:
full_sales_data.isnull().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [65]:
full_sales_data.duplicated().sum()

np.int64(14582)

In [66]:
full_sales_data = full_sales_data.drop_duplicates()

In [67]:
full_sales_data.shape

(96624, 9)

In [68]:
full_sales_data.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

---

In [69]:
## Removing the "Disc" and "Voucher Amount", since it not important

full_sales_data = full_sales_data[
    ["Date", "Voucher", "Party", "Product", "Qty", "Rate", "Gross"]
]

In [70]:
## Type Conversion of Features and also make the data consistent

full_sales_data.Date = full_sales_data.Date.str.strip()
full_sales_data.Date = pd.to_datetime(arg=full_sales_data.Date, dayfirst=True)


full_sales_data.Voucher = pd.to_numeric(
    arg=full_sales_data.Voucher.astype(str)
    .str.extract(r"(\d+)", expand=False)
    .astype("Int64")
)

full_sales_data.Party = full_sales_data.Party.str.strip().str.upper()

full_sales_data.Qty = full_sales_data.Qty.str.replace(",", "").str.strip()
full_sales_data.Qty = pd.to_numeric(arg=full_sales_data.Qty).round(2)

full_sales_data.Rate = full_sales_data.Rate.str.replace(",", "").str.strip()
full_sales_data.Rate = pd.to_numeric(arg=full_sales_data.Rate).round(2)

full_sales_data.Gross = full_sales_data.Gross.str.replace(",", "").str.strip()
full_sales_data.Gross = pd.to_numeric(arg=full_sales_data.Gross).round(2)


# full_sales_data.Disc = full_sales_data.Disc.str.replace(",", "").str.strip()
# full_sales_data.Disc = pd.to_numeric(arg=full_sales_data.Disc)
# full_sales_data["Voucher Amount"] = (
#     full_sales_data["Voucher Amount"].str.replace(",", "").str.strip()
# )
# full_sales_data["Voucher Amount"] = pd.to_numeric(arg=full_sales_data["Voucher Amount"])

In [71]:
full_sales_data.info()

<class 'pandas.DataFrame'>
Index: 96624 entries, 0 to 19175
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     95287 non-null  datetime64[us]
 1   Voucher  95287 non-null  Int64
 2   Party    96589 non-null  str
 3   Product  96420 non-null  str
 4   Qty      95323 non-null  float64
 5   Rate     95322 non-null  float64
 6   Gross    95320 non-null  float64
dtypes: Int64(1), datetime64[us](1), float64(3), str(2)
memory usage: 6.0 MB

In [72]:
full_sales_data.describe(include='all').round(4)

,Date,Voucher,Party,Product,Qty,Rate,Gross
count,95287,95287.0,96589,96420,9.532300e+04,9.532200e+04,9.532000e+04
unique,NaN,<NA>,1826,867,NaN,NaN,NaN
top,NaN,<NA>,TP13,14 GREEN,NaN,NaN,NaN
freq,NaN,<NA>,12818,2397,NaN,NaN,NaN
mean,2018-06-10 00:10:42.874683,4469.6908,NaN,NaN,5.472021e+02,7.502828e+02,9.026911e+03
min,2017-04-01 00:00:00,1.0,NaN,NaN,0.000000e+00,0.000000e+00,1.000000e+00
25%,2017-10-16 00:00:00,2048.0,NaN,NaN,1.000000e+01,1.600000e+01,7.750000e+02
50%,2018-06-05 00:00:00,4187.0,NaN,NaN,5.000000e+01,2.800000e+01,2.200000e+03
75%,2019-01-23 00:00:00,6854.0,NaN,NaN,1.500000e+02,1.400000e+02,3.500000e+03
max,2019-10-10 00:00:00,10042.0,NaN,NaN,7.593062e+06,1.002420e+07,1.178977e+08
std,NaN,2810.335,NaN,NaN,3.634327e+04,4.801254e+04,5.874586e+05

In [73]:
full_sales_data.shape

(96624, 7)

In [74]:
## Removing the record where the "Qty" and "Rate" having null value, since without this value there is no use of data

full_sales_data = full_sales_data.dropna(subset=["Qty", "Rate"], how="all")

In [75]:
full_sales_data.shape

(95323, 7)

In [76]:
## Without "Party", there is no use of that record with "Qty" and "Rate"

full_sales_data = full_sales_data.dropna(subset=["Party"])

In [77]:
full_sales_data.shape

(95289, 7)

In [78]:
## Delete the record if the data is empty

full_sales_data = full_sales_data[(full_sales_data != "").all(axis=1)]

In [79]:
full_sales_data.shape

(95289, 7)

In [80]:
## Drop the record which have NaN

full_sales_data = full_sales_data.dropna()

In [81]:
full_sales_data.shape

(95286, 7)

In [82]:
## Drop the duplicate records

full_sales_data = full_sales_data.drop_duplicates()

---

In [83]:
full_sales_data.shape

(95223, 7)

In [84]:
full_sales_data.head(10)

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0
5,2017-04-01,2,SARNESWARA TRADERS,CLASSIC ENJOY(750),1.0,1320.0,1320.0
6,2017-04-01,898,LOCK,Vishnu 250ml,100.0,30.0,3000.0
7,2017-04-01,898,LOCK,BLACK DOG-350ML,100.0,26.0,2600.0
10,2017-04-01,2497,VAMSI KRISHNA FANCY,Loose Items,1.0,800.0,800.0
13,2017-04-01,9263,VAMSI KRISHNA FANCY,Loose Items,1.0,280.0,280.0

In [85]:
full_sales_data.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
Gross      0
dtype: int64

In [86]:
full_sales_data.Party.unique()

<StringArray>
[   'SOLANKI PLASTICS',  'SARNESWARA TRADERS',                'LOCK',
 'VAMSI KRISHNA FANCY',                 'VKP',                 'KPR',
     'BALAJI PLASTICS',          'DURGAHOTEL',       'SONIYA HIRERS',
 'VENUGOPAL-INAMADUGU',
 ...
    'PRIYA PACKAGING.', 'PENCHALAYYA.M-RAPUR', 'ANJANEYULU.CH-GUDUR',
          'KGN CHIKEN',  'MARKFED-ADURUPALLI', 'SUSHMITHA CATERING-',
    'DURGA RAO-DUVVUR', 'SUBRHAMANYAM-K-ALLU',          'LAALU MALL',
 'BALAJI CHEMICALS SU']
Length: 712, dtype: str

In [87]:
full_sales_data.describe()

,Date,Voucher,Qty,Rate,Gross
count,95223,95223.0,95223.000000,95223.000000,95223.000000
mean,2018-06-09 23:17:57.584197,4469.589878,182.032403,249.897731,3005.007734
min,2017-04-01 00:00:00,1.0,0.400000,0.010000,1.000000
25%,2017-10-16 00:00:00,2047.5,10.000000,16.000000,775.000000
50%,2018-06-05 00:00:00,4187.0,50.000000,28.000000,2200.000000
75%,2019-01-23 00:00:00,6854.0,150.000000,140.000000,3480.000000
max,2019-10-10 00:00:00,10042.0,35000.000000,200000.000000,200000.000000
std,NaN,2810.207362,723.819101,2016.892468,4339.596367

In [88]:
full_sales_data.to_csv("data/final_cleaned_data_by_me.csv", index=False, )

---

# Task 2 
### Merge Function 1 Example

In [89]:
student_data = {
    "USN": ["001", "002", "003", "004", "005"],
    "Name": ["Derin", "Girish", "Monish", "Arun", "Deena"],
    "Age": [22, 21, 23, 21, 22],
}
student_mark = {
    "USN": ["001", "002", "003", "004", "005"],
    "Python": [95, 87, 64, 89, 45],
    "DSA": [88, 45, 67, 98, 78],
    "ADA": [79, 34, 90, 77, 81],
}

In [90]:
student_data = pd.DataFrame(student_data)
student_mark = pd.DataFrame(student_mark)

In [91]:
over_all_student_data = pd.merge(left=student_data, right=student_mark, how="inner")
over_all_student_data

   USN    Name  Age  Python  DSA  ADA
0  001   Derin   22      95   88   79
1  002  Girish   21      87   45   34
2  003  Monish   23      64   67   90
3  004    Arun   21      89   98   77
4  005   Deena   22      45   78   81

---

# Task 3
### List Comprehension 2 examples

##### List Comprehension 1

- Take one number from a
- Take one number from b
- Multiply them
- Include the product only if
    - the product is even
    - and product is greater than 5

In [92]:
a = [1, 2, 3, 4]
b = [2, 3, 5]

value = [x * y for x in a for y in b if (x * y % 2 == 0) and (x * y > 5)]
print(value)

[6, 10, 6, 8, 12, 20]

##### List Comprehension 2

- Take i from x
- Take j from y
- Include pair only if:
    - i != j
    - and i + j > 4

In [93]:
x = [1, 2, 3]
y = [2, 3, 4]

coordinates = [f"({i}, {j})" for i in x for j in y if (i != j) and (i + j > 4)]
print(coordinates)

['(1, 4)', '(2, 3)', '(2, 4)', '(3, 2)', '(3, 4)']

---

# Task 4
### Lambda Function 2 examples with Map, Filter, Reduce

##### Map Function 1

In [94]:
nums = [1, 2, 3, 4, 5]
square_value = map(lambda x: x * x, nums)
print(list(square_value))

[1, 4, 9, 16, 25]

##### Map Function 2

In [95]:
def name_to_upper(name):
    return name.upper()

names = ["Derin", "Girish", "Arun", "Monish", "Deena"]
name_to_upper_case = map(name_to_upper, names)
print(list(name_to_upper_case))

['DERIN', 'GIRISH', 'ARUN', 'MONISH', 'DEENA']

##### Filter Function 1

In [96]:
numbers = [1,2,3,4,5,6,7,8,9,10]
even_numbers = filter(lambda x : x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4, 6, 8, 10]

##### Filter Function 2

In [97]:
names = ["Derin", "Girish", "Arun", "Monish", "Sam", "John", "Joy"]

def find_long_name(name):
    return len(name) > 4
    
long_name = filter(find_long_name, names)
print(list(long_name))

['Derin', 'Girish', 'Monish']

##### Reduce Function 1

In [98]:
from functools import reduce

In [99]:
nums = [3,7,5,2,7]
product_of_numbers = reduce(lambda x, y: x * y, nums)
print(product_of_numbers)

1470

##### Reduce Function 2

In [100]:
names = ["Derin", "Girish", "Monish", "Nandha", "Harshavardan"]

def find_longest_name(name1, name2):
    return name1 if len(name1) > len(name2) else name2

longest_name = reduce(find_longest_name, names)
print(longest_name)

Harshavardan

---

# Cleaned Data Provied by Coach for Checking

In [101]:
cleaned_data = pd.read_csv("data/Sales-Transactions-Edited.csv")

In [102]:
cleaned_data.shape

(95562, 6)

In [103]:
cleaned_data['Party'].unique()

<StringArray>
[   'SOLANKI PLASTICS',  'SARNESWARA TRADERS',                'LOCK',
 'VAMSI KRISHNA FANCY',                 'VKP',      'KARIMULLA-BTTR',
             'SVS-ALR',       'LAVANYA FANCY',     'CHEKKA SUDHAKAR',
  'KRISHNA AYYAPAGUDI',
 ...
  'MARKFED-ADURUPALLI', 'SUSHMITHA CATERING-', 'SUBRHAMANYAM-CHEJAR',
    'DURGA RAO-DUVVUR', 'SUBRHAMANYAM-K-ALLU',             'COLOURS',
 'CHANDRAMOHAN REDDY-',         'RACHANA-NLR',   'MUNEER-BITRAGUNTA',
 'BOLLINENI HOSPITAL-']
Length: 712, dtype: str