# Chapter 3 - Task 1

#### Scripting-Based Questions

#### 1.	Write a program to take a name and age from the user and print a greeting message.

In [173]:
name = input("Enter your name: ")
age = int(input("Enter you age: "))

print(f"Hi {name}, you are {age} old")

Hi Derin, you are 22 old

#### 2.	Create a list of numbers and print only even numbers using a for loop.

In [174]:
num = int(input("Enter the number get even from 0: "))
for i in range(num+1):
    if i % 2 == 0:
        print(i)

0
2
4
6
8
10
12
14
16
18
20

#### 3.	Write a program that handles division by zero using try-except.

In [175]:
num1 = int(input("Enter the value of num1: "))
num2 = int(input("Enter the value of num2: "))

try:
    result = num1/num2
    print(f"{num1} / {num2} = {result}")

except ZeroDivisionError:
    print("Divsion by zero is not possible.")

Divsion by zero is not possible.

#### 4.	Given a string, count how many vowels it has.

In [176]:
word = input("Enter the word to Count vowel letter in it: ").lower()
count = 0
for i in word:
    if i in "aeiou":
        count += 1
        
if count > 0:
    print(f"Your word have {count} vowel letters")
else:
    print(f"Your word have no vowel letters")

Your word have 4 vowel letters

#### 5.	Reverse a list without using built-in functions.

In [177]:
list = [1,2,3,4,5,6,7,8,9,10]
rev_list = list[::-1]
print(f"Original List: {list}")
print(f"Reversed List: {rev_list}")

Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Reversed List: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

#### 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [178]:
student_data = {
    "USN" : ["001", "002", "003", "004", "005"],
    "Name" : ["Derin", "Girish", "Monish", "Arun", "Deena"],
    "Age" : [22, 21, 23, 21, 22],
    "Course" : ["B.E", "B.Tech", "MBA", "M.E", "M.Tech"],
    "CGPA" : [8.3, 9.9, 9.4, 7.1, 6.5]
}
student_data

{'USN': ['001', '002', '003', '004', '005'],
 'Name': ['Derin', 'Girish', 'Monish', 'Arun', 'Deena'],
 'Age': [22, 21, 23, 21, 22],
 'Course': ['B.E', 'B.Tech', 'MBA', 'M.E', 'M.Tech'],
 'CGPA': [8.3, 9.9, 9.4, 7.1, 6.5]}

#### 7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [179]:
import pandas as pd

In [180]:
employee_data = pd.read_csv("data/Employee_data.csv")
employee_data.head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62000.0  12/11/2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

#### 8.	Create a DataFrame from a Python dictionary.

In [181]:
student_data = {
    "USN": ["001", "002", "003", "004", "005"],
    "Name": ["Derin", "Girish", "Monish", "Arun", "Deena"],
    "Age": [22, 21, 23, 21, 22],
    "Course": ["B.E", "B.Tech", "MBA", "M.E", "M.Tech"],
    "CGPA": [8.3, 9.9, 9.4, 7.1, 6.5],
}

student_data_table = pd.DataFrame(data=student_data)
student_data_table

   USN    Name  Age  Course  CGPA
0  001   Derin   22     B.E   8.3
1  002  Girish   21  B.Tech   9.9
2  003  Monish   23     MBA   9.4
3  004    Arun   21     M.E   7.1
4  005   Deena   22  M.Tech   6.5

#### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [182]:
employee_data = pd.read_csv("data/Employee_data.csv")
employee_data

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  12/11/2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0   10/9/2022
7          Roshan  31.0    IT Tech      NaN  12/11/2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  12/11/2020
11        Mathiew   NaN    Support  58000.0  15-01-2025
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

In [183]:
employee_data.isnull().sum()

Name          1
Age           2
Department    0
Salary        5
Join_Date     1
dtype: int64

In [184]:
employee_data["Join_Date"] = pd.to_datetime(employee_data["Join_Date"], dayfirst=True, format="mixed")

In [185]:
## 👉 Method - 1

# employee_data["Salary"] = employee_data["Salary"].fillna(employee_data["Salary"].mean())
# employee_data["Age"] = employee_data["Age"].fillna(round(employee_data["Age"].mean()))
# employee_data["Name"] = employee_data["Name"].fillna("Unknown")
# employee_data["Join_Date"] = employee_data["Join_Date"].fillna(employee_data["Join_Date"].mode()[0])
# employee_data

In [186]:
## 👉 Method - 2

employee_data.fillna({
    "Salary" : employee_data["Salary"].mean(),
    "Age" : round(employee_data["Age"].mean()),
    "Name" : "Unknown",
    "Join_Date" : employee_data["Join_Date"].mode()[0]
}, inplace=True)

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathiew  30.0    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6         Unknown  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech  62000.0 2020-11-12
8       Kuppusamy  28.0        Ops  62000.0 2021-05-21
9           Ajesh  28.0    Support  62000.0 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-11-12
11        Mathiew  30.0    Support  58000.0 2025-01-15
12  Jagadheeswari  28.0    IT Tech  62000.0 2020-11-12
13           Mani  28.0        Ops  62000.0 2021-05-21

In [187]:
employee_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

#### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

In [188]:
employee_data[employee_data["Age"] > 30]

       Name   Age Department   Salary  Join_Date
1     Nasir  31.0    IT Tech  62000.0 2020-11-12
5     Navin  35.0    Support  72000.0 2023-08-19
6   Unknown  40.0    IT Tech  64000.0 2022-09-10
7    Roshan  31.0    IT Tech  62000.0 2020-11-12
10     Diya  31.0    IT Tech  63000.0 2020-11-12